package kit

var (
	countries = []*Country{
		{
			NameEng:        "Russia",
			TranslationKey: "countries.rus",
			Code:           "643",
			Alfa2:          "RU",
			Alfa3:          "RUS",
			TimeZones:      []string{TzP12, TzP11, TzP10, TzP9, TzP8, TzP7, TzP6, TzP5, TzP4, TzP3, TzP2},
			PhoneCodes:     []string{"7"},
			Currencies:     GetCurrencies(CurRUB),
		},
		{
			NameEng:        "Albania",
			TranslationKey: "countries.alb",
			Code:           "008",
			Alfa2:          "AL",
			Alfa3:          "ALB",
			TimeZones:      []string{TzP1, TzP2},
			PhoneCodes:     []string{"355"},
			Currencies:     GetCurrencies(CurALL, CurEUR),
			DstSwitchMode:  DstSwitchModeMarchLastSundayOctoberLastSunday,
		},
		{
			NameEng:        "Bosnia and Herzegovina",
			TranslationKey: "countries.bih",
			Code:           "070",
			Alfa2:          "BA",
			Alfa3:          "BIH",
			TimeZones:      []string{TzP1, TzP2},
			PhoneCodes:     []string{"387"},
			Currencies:     GetCurrencies(CurBAM),
			DstSwitchMode:  DstSwitchModeMarchLastSundayOctoberLastSunday,
		},
		{
			NameEng:        "Montenegro",
			TranslationKey: "countries.mne",
			Code:           "499",
			Alfa2:          "ME",
			Alfa3:          "MNE",
			TimeZones:      []string{TzP1, TzP2},
			PhoneCodes:     []string{"382"},
			Currencies:     GetCurrencies(CurEUR),
			DstSwitchMode:  DstSwitchModeMarchLastSundayOctoberLastSunday,
		},
		{
			NameEng:        "Serbia",
			TranslationKey: "countries.srb",
			Code:           "688",
			Alfa2:          "RS",
			Alfa3:          "SRB",
			TimeZones:      []string{TzP1, TzP2},
			PhoneCodes:     []string{"381"},
			Currencies:     GetCurrencies(CurRSD, CurEUR),
			DstSwitchMode:  DstSwitchModeMarchLastSundayOctoberLastSunday,
		},
		{
			NameEng:        "Croatia",
			TranslationKey: "countries.hrv",
			Code:           "191",
			Alfa2:          "HR",
			Alfa3:          "HRV",
			TimeZones:      []string{TzP2},
			PhoneCodes:     []string{"385"},
			Currencies:     GetCurrencies(CurHRK, CurEUR),
			DstSwitchMode:  DstSwitchModeMarchLastSundayOctoberLastSunday,
		},
		{
			NameEng:        "Slovenia",
			TranslationKey: "countries.svn",
			Code:           "705",
			Alfa2:          "SI",
			Alfa3:          "SVN",
			TimeZones:      []string{TzP1, TzP2},
			PhoneCodes:     []string{"386"},
			Currencies:     GetCurrencies(CurEUR),
			DstSwitchMode:  DstSwitchModeMarchLastSundayOctoberLastSunday,
		},
	}
)
