// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/aerospike/aerospike-client-go/v7"
	"github.com/mikhailbolshakov/kit"
	aerospike0 "github.com/mikhailbolshakov/kit/storages/aerospike"
	mock "github.com/stretchr/testify/mock"
)

// NewAerospikeAerospike creates a new instance of AerospikeAerospike. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAerospikeAerospike(t interface {
	mock.TestingT
	Cleanup(func())
}) *AerospikeAerospike {
	mock := &AerospikeAerospike{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// AerospikeAerospike is an autogenerated mock type for the Aerospike type
type AerospikeAerospike struct {
	mock.Mock
}

type AerospikeAerospike_Expecter struct {
	mock *mock.Mock
}

func (_m *AerospikeAerospike) EXPECT() *AerospikeAerospike_Expecter {
	return &AerospikeAerospike_Expecter{mock: &_m.Mock}
}

// Close provides a mock function for the type AerospikeAerospike
func (_mock *AerospikeAerospike) Close(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// AerospikeAerospike_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type AerospikeAerospike_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
//   - ctx
func (_e *AerospikeAerospike_Expecter) Close(ctx interface{}) *AerospikeAerospike_Close_Call {
	return &AerospikeAerospike_Close_Call{Call: _e.mock.On("Close", ctx)}
}

func (_c *AerospikeAerospike_Close_Call) Run(run func(ctx context.Context)) *AerospikeAerospike_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *AerospikeAerospike_Close_Call) Return(err error) *AerospikeAerospike_Close_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *AerospikeAerospike_Close_Call) RunAndReturn(run func(ctx context.Context) error) *AerospikeAerospike_Close_Call {
	_c.Call.Return(run)
	return _c
}

// GetKey provides a mock function for the type AerospikeAerospike
func (_mock *AerospikeAerospike) GetKey(ctx context.Context, ns string, key interface{}) (*aerospike.Key, error) {
	ret := _mock.Called(ctx, ns, key)

	if len(ret) == 0 {
		panic("no return value specified for GetKey")
	}

	var r0 *aerospike.Key
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, interface{}) (*aerospike.Key, error)); ok {
		return returnFunc(ctx, ns, key)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, interface{}) *aerospike.Key); ok {
		r0 = returnFunc(ctx, ns, key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*aerospike.Key)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, interface{}) error); ok {
		r1 = returnFunc(ctx, ns, key)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// AerospikeAerospike_GetKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetKey'
type AerospikeAerospike_GetKey_Call struct {
	*mock.Call
}

// GetKey is a helper method to define mock.On call
//   - ctx
//   - ns
//   - key
func (_e *AerospikeAerospike_Expecter) GetKey(ctx interface{}, ns interface{}, key interface{}) *AerospikeAerospike_GetKey_Call {
	return &AerospikeAerospike_GetKey_Call{Call: _e.mock.On("GetKey", ctx, ns, key)}
}

func (_c *AerospikeAerospike_GetKey_Call) Run(run func(ctx context.Context, ns string, key interface{})) *AerospikeAerospike_GetKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(interface{}))
	})
	return _c
}

func (_c *AerospikeAerospike_GetKey_Call) Return(key1 *aerospike.Key, err error) *AerospikeAerospike_GetKey_Call {
	_c.Call.Return(key1, err)
	return _c
}

func (_c *AerospikeAerospike_GetKey_Call) RunAndReturn(run func(ctx context.Context, ns string, key interface{}) (*aerospike.Key, error)) *AerospikeAerospike_GetKey_Call {
	_c.Call.Return(run)
	return _c
}

// Instance provides a mock function for the type AerospikeAerospike
func (_mock *AerospikeAerospike) Instance() *aerospike.Client {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Instance")
	}

	var r0 *aerospike.Client
	if returnFunc, ok := ret.Get(0).(func() *aerospike.Client); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*aerospike.Client)
		}
	}
	return r0
}

// AerospikeAerospike_Instance_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Instance'
type AerospikeAerospike_Instance_Call struct {
	*mock.Call
}

// Instance is a helper method to define mock.On call
func (_e *AerospikeAerospike_Expecter) Instance() *AerospikeAerospike_Instance_Call {
	return &AerospikeAerospike_Instance_Call{Call: _e.mock.On("Instance")}
}

func (_c *AerospikeAerospike_Instance_Call) Run(run func()) *AerospikeAerospike_Instance_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *AerospikeAerospike_Instance_Call) Return(client *aerospike.Client) *AerospikeAerospike_Instance_Call {
	_c.Call.Return(client)
	return _c
}

func (_c *AerospikeAerospike_Instance_Call) RunAndReturn(run func() *aerospike.Client) *AerospikeAerospike_Instance_Call {
	_c.Call.Return(run)
	return _c
}

// Open provides a mock function for the type AerospikeAerospike
func (_mock *AerospikeAerospike) Open(ctx context.Context, cfg *aerospike0.Config, logger kit.CLoggerFunc) error {
	ret := _mock.Called(ctx, cfg, logger)

	if len(ret) == 0 {
		panic("no return value specified for Open")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *aerospike0.Config, kit.CLoggerFunc) error); ok {
		r0 = returnFunc(ctx, cfg, logger)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// AerospikeAerospike_Open_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Open'
type AerospikeAerospike_Open_Call struct {
	*mock.Call
}

// Open is a helper method to define mock.On call
//   - ctx
//   - cfg
//   - logger
func (_e *AerospikeAerospike_Expecter) Open(ctx interface{}, cfg interface{}, logger interface{}) *AerospikeAerospike_Open_Call {
	return &AerospikeAerospike_Open_Call{Call: _e.mock.On("Open", ctx, cfg, logger)}
}

func (_c *AerospikeAerospike_Open_Call) Run(run func(ctx context.Context, cfg *aerospike0.Config, logger kit.CLoggerFunc)) *AerospikeAerospike_Open_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*aerospike0.Config), args[2].(kit.CLoggerFunc))
	})
	return _c
}

func (_c *AerospikeAerospike_Open_Call) Return(err error) *AerospikeAerospike_Open_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *AerospikeAerospike_Open_Call) RunAndReturn(run func(ctx context.Context, cfg *aerospike0.Config, logger kit.CLoggerFunc) error) *AerospikeAerospike_Open_Call {
	_c.Call.Return(run)
	return _c
}

// Reconnect provides a mock function for the type AerospikeAerospike
func (_mock *AerospikeAerospike) Reconnect(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Reconnect")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// AerospikeAerospike_Reconnect_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Reconnect'
type AerospikeAerospike_Reconnect_Call struct {
	*mock.Call
}

// Reconnect is a helper method to define mock.On call
//   - ctx
func (_e *AerospikeAerospike_Expecter) Reconnect(ctx interface{}) *AerospikeAerospike_Reconnect_Call {
	return &AerospikeAerospike_Reconnect_Call{Call: _e.mock.On("Reconnect", ctx)}
}

func (_c *AerospikeAerospike_Reconnect_Call) Run(run func(ctx context.Context)) *AerospikeAerospike_Reconnect_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *AerospikeAerospike_Reconnect_Call) Return(err error) *AerospikeAerospike_Reconnect_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *AerospikeAerospike_Reconnect_Call) RunAndReturn(run func(ctx context.Context) error) *AerospikeAerospike_Reconnect_Call {
	_c.Call.Return(run)
	return _c
}
