// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/mikhailbolshakov/kit"
	"github.com/mikhailbolshakov/kit/localization"
	mock "github.com/stretchr/testify/mock"
)

// NewLocalizationTranslatable creates a new instance of LocalizationTranslatable. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewLocalizationTranslatable(t interface {
	mock.TestingT
	Cleanup(func())
}) *LocalizationTranslatable {
	mock := &LocalizationTranslatable{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// LocalizationTranslatable is an autogenerated mock type for the Translatable type
type LocalizationTranslatable struct {
	mock.Mock
}

type LocalizationTranslatable_Expecter struct {
	mock *mock.Mock
}

func (_m *LocalizationTranslatable) EXPECT() *LocalizationTranslatable_Expecter {
	return &LocalizationTranslatable_Expecter{mock: &_m.Mock}
}

// GetTranslatedKeys provides a mock function for the type LocalizationTranslatable
func (_mock *LocalizationTranslatable) GetTranslatedKeys() []string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetTranslatedKeys")
	}

	var r0 []string
	if returnFunc, ok := ret.Get(0).(func() []string); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	return r0
}

// LocalizationTranslatable_GetTranslatedKeys_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTranslatedKeys'
type LocalizationTranslatable_GetTranslatedKeys_Call struct {
	*mock.Call
}

// GetTranslatedKeys is a helper method to define mock.On call
func (_e *LocalizationTranslatable_Expecter) GetTranslatedKeys() *LocalizationTranslatable_GetTranslatedKeys_Call {
	return &LocalizationTranslatable_GetTranslatedKeys_Call{Call: _e.mock.On("GetTranslatedKeys")}
}

func (_c *LocalizationTranslatable_GetTranslatedKeys_Call) Run(run func()) *LocalizationTranslatable_GetTranslatedKeys_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *LocalizationTranslatable_GetTranslatedKeys_Call) Return(strings []string) *LocalizationTranslatable_GetTranslatedKeys_Call {
	_c.Call.Return(strings)
	return _c
}

func (_c *LocalizationTranslatable_GetTranslatedKeys_Call) RunAndReturn(run func() []string) *LocalizationTranslatable_GetTranslatedKeys_Call {
	_c.Call.Return(run)
	return _c
}

// NewLocalizationDataTranslationService creates a new instance of LocalizationDataTranslationService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewLocalizationDataTranslationService(t interface {
	mock.TestingT
	Cleanup(func())
}) *LocalizationDataTranslationService {
	mock := &LocalizationDataTranslationService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// LocalizationDataTranslationService is an autogenerated mock type for the DataTranslationService type
type LocalizationDataTranslationService struct {
	mock.Mock
}

type LocalizationDataTranslationService_Expecter struct {
	mock *mock.Mock
}

func (_m *LocalizationDataTranslationService) EXPECT() *LocalizationDataTranslationService_Expecter {
	return &LocalizationDataTranslationService_Expecter{mock: &_m.Mock}
}

// BuildKey provides a mock function for the type LocalizationDataTranslationService
func (_mock *LocalizationDataTranslationService) BuildKey(category string, id string) string {
	ret := _mock.Called(category, id)

	if len(ret) == 0 {
		panic("no return value specified for BuildKey")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func(string, string) string); ok {
		r0 = returnFunc(category, id)
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// LocalizationDataTranslationService_BuildKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BuildKey'
type LocalizationDataTranslationService_BuildKey_Call struct {
	*mock.Call
}

// BuildKey is a helper method to define mock.On call
//   - category
//   - id
func (_e *LocalizationDataTranslationService_Expecter) BuildKey(category interface{}, id interface{}) *LocalizationDataTranslationService_BuildKey_Call {
	return &LocalizationDataTranslationService_BuildKey_Call{Call: _e.mock.On("BuildKey", category, id)}
}

func (_c *LocalizationDataTranslationService_BuildKey_Call) Run(run func(category string, id string)) *LocalizationDataTranslationService_BuildKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *LocalizationDataTranslationService_BuildKey_Call) Return(s string) *LocalizationDataTranslationService_BuildKey_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *LocalizationDataTranslationService_BuildKey_Call) RunAndReturn(run func(category string, id string) string) *LocalizationDataTranslationService_BuildKey_Call {
	_c.Call.Return(run)
	return _c
}

// GenKey provides a mock function for the type LocalizationDataTranslationService
func (_mock *LocalizationDataTranslationService) GenKey(category string) string {
	ret := _mock.Called(category)

	if len(ret) == 0 {
		panic("no return value specified for GenKey")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func(string) string); ok {
		r0 = returnFunc(category)
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// LocalizationDataTranslationService_GenKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GenKey'
type LocalizationDataTranslationService_GenKey_Call struct {
	*mock.Call
}

// GenKey is a helper method to define mock.On call
//   - category
func (_e *LocalizationDataTranslationService_Expecter) GenKey(category interface{}) *LocalizationDataTranslationService_GenKey_Call {
	return &LocalizationDataTranslationService_GenKey_Call{Call: _e.mock.On("GenKey", category)}
}

func (_c *LocalizationDataTranslationService_GenKey_Call) Run(run func(category string)) *LocalizationDataTranslationService_GenKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *LocalizationDataTranslationService_GenKey_Call) Return(s string) *LocalizationDataTranslationService_GenKey_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *LocalizationDataTranslationService_GenKey_Call) RunAndReturn(run func(category string) string) *LocalizationDataTranslationService_GenKey_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type LocalizationDataTranslationService
func (_mock *LocalizationDataTranslationService) Get(ctx context.Context, key string, lang string) (*localization.Translation, error) {
	ret := _mock.Called(ctx, key, lang)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *localization.Translation
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (*localization.Translation, error)); ok {
		return returnFunc(ctx, key, lang)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) *localization.Translation); ok {
		r0 = returnFunc(ctx, key, lang)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*localization.Translation)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, key, lang)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// LocalizationDataTranslationService_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type LocalizationDataTranslationService_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx
//   - key
//   - lang
func (_e *LocalizationDataTranslationService_Expecter) Get(ctx interface{}, key interface{}, lang interface{}) *LocalizationDataTranslationService_Get_Call {
	return &LocalizationDataTranslationService_Get_Call{Call: _e.mock.On("Get", ctx, key, lang)}
}

func (_c *LocalizationDataTranslationService_Get_Call) Run(run func(ctx context.Context, key string, lang string)) *LocalizationDataTranslationService_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *LocalizationDataTranslationService_Get_Call) Return(translation *localization.Translation, err error) *LocalizationDataTranslationService_Get_Call {
	_c.Call.Return(translation, err)
	return _c
}

func (_c *LocalizationDataTranslationService_Get_Call) RunAndReturn(run func(ctx context.Context, key string, lang string) (*localization.Translation, error)) *LocalizationDataTranslationService_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Merge provides a mock function for the type LocalizationDataTranslationService
func (_mock *LocalizationDataTranslationService) Merge(ctx context.Context, t ...*localization.TranslationByKey) ([]string, error) {
	var tmpRet mock.Arguments
	if len(t) > 0 {
		tmpRet = _mock.Called(ctx, t)
	} else {
		tmpRet = _mock.Called(ctx)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Merge")
	}

	var r0 []string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ...*localization.TranslationByKey) ([]string, error)); ok {
		return returnFunc(ctx, t...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, ...*localization.TranslationByKey) []string); ok {
		r0 = returnFunc(ctx, t...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, ...*localization.TranslationByKey) error); ok {
		r1 = returnFunc(ctx, t...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// LocalizationDataTranslationService_Merge_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Merge'
type LocalizationDataTranslationService_Merge_Call struct {
	*mock.Call
}

// Merge is a helper method to define mock.On call
//   - ctx
//   - t
func (_e *LocalizationDataTranslationService_Expecter) Merge(ctx interface{}, t ...interface{}) *LocalizationDataTranslationService_Merge_Call {
	return &LocalizationDataTranslationService_Merge_Call{Call: _e.mock.On("Merge",
		append([]interface{}{ctx}, t...)...)}
}

func (_c *LocalizationDataTranslationService_Merge_Call) Run(run func(ctx context.Context, t ...*localization.TranslationByKey)) *LocalizationDataTranslationService_Merge_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := args[1].([]*localization.TranslationByKey)
		run(args[0].(context.Context), variadicArgs...)
	})
	return _c
}

func (_c *LocalizationDataTranslationService_Merge_Call) Return(strings []string, err error) *LocalizationDataTranslationService_Merge_Call {
	_c.Call.Return(strings, err)
	return _c
}

func (_c *LocalizationDataTranslationService_Merge_Call) RunAndReturn(run func(ctx context.Context, t ...*localization.TranslationByKey) ([]string, error)) *LocalizationDataTranslationService_Merge_Call {
	_c.Call.Return(run)
	return _c
}

// MustGet provides a mock function for the type LocalizationDataTranslationService
func (_mock *LocalizationDataTranslationService) MustGet(ctx context.Context, key string, lang string) (*localization.Translation, error) {
	ret := _mock.Called(ctx, key, lang)

	if len(ret) == 0 {
		panic("no return value specified for MustGet")
	}

	var r0 *localization.Translation
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (*localization.Translation, error)); ok {
		return returnFunc(ctx, key, lang)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) *localization.Translation); ok {
		r0 = returnFunc(ctx, key, lang)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*localization.Translation)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, key, lang)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// LocalizationDataTranslationService_MustGet_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MustGet'
type LocalizationDataTranslationService_MustGet_Call struct {
	*mock.Call
}

// MustGet is a helper method to define mock.On call
//   - ctx
//   - key
//   - lang
func (_e *LocalizationDataTranslationService_Expecter) MustGet(ctx interface{}, key interface{}, lang interface{}) *LocalizationDataTranslationService_MustGet_Call {
	return &LocalizationDataTranslationService_MustGet_Call{Call: _e.mock.On("MustGet", ctx, key, lang)}
}

func (_c *LocalizationDataTranslationService_MustGet_Call) Run(run func(ctx context.Context, key string, lang string)) *LocalizationDataTranslationService_MustGet_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *LocalizationDataTranslationService_MustGet_Call) Return(translation *localization.Translation, err error) *LocalizationDataTranslationService_MustGet_Call {
	_c.Call.Return(translation, err)
	return _c
}

func (_c *LocalizationDataTranslationService_MustGet_Call) RunAndReturn(run func(ctx context.Context, key string, lang string) (*localization.Translation, error)) *LocalizationDataTranslationService_MustGet_Call {
	_c.Call.Return(run)
	return _c
}

// MustGetByKeys provides a mock function for the type LocalizationDataTranslationService
func (_mock *LocalizationDataTranslationService) MustGetByKeys(ctx context.Context, lang string, keys []string) (map[string]*localization.Translation, error) {
	ret := _mock.Called(ctx, lang, keys)

	if len(ret) == 0 {
		panic("no return value specified for MustGetByKeys")
	}

	var r0 map[string]*localization.Translation
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []string) (map[string]*localization.Translation, error)); ok {
		return returnFunc(ctx, lang, keys)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []string) map[string]*localization.Translation); ok {
		r0 = returnFunc(ctx, lang, keys)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]*localization.Translation)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, []string) error); ok {
		r1 = returnFunc(ctx, lang, keys)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// LocalizationDataTranslationService_MustGetByKeys_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MustGetByKeys'
type LocalizationDataTranslationService_MustGetByKeys_Call struct {
	*mock.Call
}

// MustGetByKeys is a helper method to define mock.On call
//   - ctx
//   - lang
//   - keys
func (_e *LocalizationDataTranslationService_Expecter) MustGetByKeys(ctx interface{}, lang interface{}, keys interface{}) *LocalizationDataTranslationService_MustGetByKeys_Call {
	return &LocalizationDataTranslationService_MustGetByKeys_Call{Call: _e.mock.On("MustGetByKeys", ctx, lang, keys)}
}

func (_c *LocalizationDataTranslationService_MustGetByKeys_Call) Run(run func(ctx context.Context, lang string, keys []string)) *LocalizationDataTranslationService_MustGetByKeys_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].([]string))
	})
	return _c
}

func (_c *LocalizationDataTranslationService_MustGetByKeys_Call) Return(stringToTranslation map[string]*localization.Translation, err error) *LocalizationDataTranslationService_MustGetByKeys_Call {
	_c.Call.Return(stringToTranslation, err)
	return _c
}

func (_c *LocalizationDataTranslationService_MustGetByKeys_Call) RunAndReturn(run func(ctx context.Context, lang string, keys []string) (map[string]*localization.Translation, error)) *LocalizationDataTranslationService_MustGetByKeys_Call {
	_c.Call.Return(run)
	return _c
}

// MustTranslateObjects provides a mock function for the type LocalizationDataTranslationService
func (_mock *LocalizationDataTranslationService) MustTranslateObjects(ctx context.Context, lang string, objs ...localization.Translatable) localization.TranslationKV {
	var tmpRet mock.Arguments
	if len(objs) > 0 {
		tmpRet = _mock.Called(ctx, lang, objs)
	} else {
		tmpRet = _mock.Called(ctx, lang)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for MustTranslateObjects")
	}

	var r0 localization.TranslationKV
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...localization.Translatable) localization.TranslationKV); ok {
		r0 = returnFunc(ctx, lang, objs...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(localization.TranslationKV)
		}
	}
	return r0
}

// LocalizationDataTranslationService_MustTranslateObjects_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MustTranslateObjects'
type LocalizationDataTranslationService_MustTranslateObjects_Call struct {
	*mock.Call
}

// MustTranslateObjects is a helper method to define mock.On call
//   - ctx
//   - lang
//   - objs
func (_e *LocalizationDataTranslationService_Expecter) MustTranslateObjects(ctx interface{}, lang interface{}, objs ...interface{}) *LocalizationDataTranslationService_MustTranslateObjects_Call {
	return &LocalizationDataTranslationService_MustTranslateObjects_Call{Call: _e.mock.On("MustTranslateObjects",
		append([]interface{}{ctx, lang}, objs...)...)}
}

func (_c *LocalizationDataTranslationService_MustTranslateObjects_Call) Run(run func(ctx context.Context, lang string, objs ...localization.Translatable)) *LocalizationDataTranslationService_MustTranslateObjects_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := args[2].([]localization.Translatable)
		run(args[0].(context.Context), args[1].(string), variadicArgs...)
	})
	return _c
}

func (_c *LocalizationDataTranslationService_MustTranslateObjects_Call) Return(translationKV localization.TranslationKV) *LocalizationDataTranslationService_MustTranslateObjects_Call {
	_c.Call.Return(translationKV)
	return _c
}

func (_c *LocalizationDataTranslationService_MustTranslateObjects_Call) RunAndReturn(run func(ctx context.Context, lang string, objs ...localization.Translatable) localization.TranslationKV) *LocalizationDataTranslationService_MustTranslateObjects_Call {
	_c.Call.Return(run)
	return _c
}

// Search provides a mock function for the type LocalizationDataTranslationService
func (_mock *LocalizationDataTranslationService) Search(ctx context.Context, cr *kit.PagingRequestG[localization.GetTranslationsCriteria]) (*kit.PagingResponseG[localization.TranslationByKey], error) {
	ret := _mock.Called(ctx, cr)

	if len(ret) == 0 {
		panic("no return value specified for Search")
	}

	var r0 *kit.PagingResponseG[localization.TranslationByKey]
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *kit.PagingRequestG[localization.GetTranslationsCriteria]) (*kit.PagingResponseG[localization.TranslationByKey], error)); ok {
		return returnFunc(ctx, cr)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *kit.PagingRequestG[localization.GetTranslationsCriteria]) *kit.PagingResponseG[localization.TranslationByKey]); ok {
		r0 = returnFunc(ctx, cr)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*kit.PagingResponseG[localization.TranslationByKey])
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *kit.PagingRequestG[localization.GetTranslationsCriteria]) error); ok {
		r1 = returnFunc(ctx, cr)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// LocalizationDataTranslationService_Search_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Search'
type LocalizationDataTranslationService_Search_Call struct {
	*mock.Call
}

// Search is a helper method to define mock.On call
//   - ctx
//   - cr
func (_e *LocalizationDataTranslationService_Expecter) Search(ctx interface{}, cr interface{}) *LocalizationDataTranslationService_Search_Call {
	return &LocalizationDataTranslationService_Search_Call{Call: _e.mock.On("Search", ctx, cr)}
}

func (_c *LocalizationDataTranslationService_Search_Call) Run(run func(ctx context.Context, cr *kit.PagingRequestG[localization.GetTranslationsCriteria])) *LocalizationDataTranslationService_Search_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*kit.PagingRequestG[localization.GetTranslationsCriteria]))
	})
	return _c
}

func (_c *LocalizationDataTranslationService_Search_Call) Return(pagingResponseG *kit.PagingResponseG[localization.TranslationByKey], err error) *LocalizationDataTranslationService_Search_Call {
	_c.Call.Return(pagingResponseG, err)
	return _c
}

func (_c *LocalizationDataTranslationService_Search_Call) RunAndReturn(run func(ctx context.Context, cr *kit.PagingRequestG[localization.GetTranslationsCriteria]) (*kit.PagingResponseG[localization.TranslationByKey], error)) *LocalizationDataTranslationService_Search_Call {
	_c.Call.Return(run)
	return _c
}

// TranslateObjects provides a mock function for the type LocalizationDataTranslationService
func (_mock *LocalizationDataTranslationService) TranslateObjects(ctx context.Context, lang string, objs ...localization.Translatable) (localization.TranslationKV, error) {
	var tmpRet mock.Arguments
	if len(objs) > 0 {
		tmpRet = _mock.Called(ctx, lang, objs)
	} else {
		tmpRet = _mock.Called(ctx, lang)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for TranslateObjects")
	}

	var r0 localization.TranslationKV
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...localization.Translatable) (localization.TranslationKV, error)); ok {
		return returnFunc(ctx, lang, objs...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...localization.Translatable) localization.TranslationKV); ok {
		r0 = returnFunc(ctx, lang, objs...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(localization.TranslationKV)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, ...localization.Translatable) error); ok {
		r1 = returnFunc(ctx, lang, objs...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// LocalizationDataTranslationService_TranslateObjects_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TranslateObjects'
type LocalizationDataTranslationService_TranslateObjects_Call struct {
	*mock.Call
}

// TranslateObjects is a helper method to define mock.On call
//   - ctx
//   - lang
//   - objs
func (_e *LocalizationDataTranslationService_Expecter) TranslateObjects(ctx interface{}, lang interface{}, objs ...interface{}) *LocalizationDataTranslationService_TranslateObjects_Call {
	return &LocalizationDataTranslationService_TranslateObjects_Call{Call: _e.mock.On("TranslateObjects",
		append([]interface{}{ctx, lang}, objs...)...)}
}

func (_c *LocalizationDataTranslationService_TranslateObjects_Call) Run(run func(ctx context.Context, lang string, objs ...localization.Translatable)) *LocalizationDataTranslationService_TranslateObjects_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := args[2].([]localization.Translatable)
		run(args[0].(context.Context), args[1].(string), variadicArgs...)
	})
	return _c
}

func (_c *LocalizationDataTranslationService_TranslateObjects_Call) Return(translationKV localization.TranslationKV, err error) *LocalizationDataTranslationService_TranslateObjects_Call {
	_c.Call.Return(translationKV, err)
	return _c
}

func (_c *LocalizationDataTranslationService_TranslateObjects_Call) RunAndReturn(run func(ctx context.Context, lang string, objs ...localization.Translatable) (localization.TranslationKV, error)) *LocalizationDataTranslationService_TranslateObjects_Call {
	_c.Call.Return(run)
	return _c
}

// NewLocalizationDataTranslationStorage creates a new instance of LocalizationDataTranslationStorage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewLocalizationDataTranslationStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *LocalizationDataTranslationStorage {
	mock := &LocalizationDataTranslationStorage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// LocalizationDataTranslationStorage is an autogenerated mock type for the DataTranslationStorage type
type LocalizationDataTranslationStorage struct {
	mock.Mock
}

type LocalizationDataTranslationStorage_Expecter struct {
	mock *mock.Mock
}

func (_m *LocalizationDataTranslationStorage) EXPECT() *LocalizationDataTranslationStorage_Expecter {
	return &LocalizationDataTranslationStorage_Expecter{mock: &_m.Mock}
}

// EnsureTranslationFields provides a mock function for the type LocalizationDataTranslationStorage
func (_mock *LocalizationDataTranslationStorage) EnsureTranslationFields(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for EnsureTranslationFields")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// LocalizationDataTranslationStorage_EnsureTranslationFields_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EnsureTranslationFields'
type LocalizationDataTranslationStorage_EnsureTranslationFields_Call struct {
	*mock.Call
}

// EnsureTranslationFields is a helper method to define mock.On call
//   - ctx
func (_e *LocalizationDataTranslationStorage_Expecter) EnsureTranslationFields(ctx interface{}) *LocalizationDataTranslationStorage_EnsureTranslationFields_Call {
	return &LocalizationDataTranslationStorage_EnsureTranslationFields_Call{Call: _e.mock.On("EnsureTranslationFields", ctx)}
}

func (_c *LocalizationDataTranslationStorage_EnsureTranslationFields_Call) Run(run func(ctx context.Context)) *LocalizationDataTranslationStorage_EnsureTranslationFields_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *LocalizationDataTranslationStorage_EnsureTranslationFields_Call) Return(err error) *LocalizationDataTranslationStorage_EnsureTranslationFields_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *LocalizationDataTranslationStorage_EnsureTranslationFields_Call) RunAndReturn(run func(ctx context.Context) error) *LocalizationDataTranslationStorage_EnsureTranslationFields_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type LocalizationDataTranslationStorage
func (_mock *LocalizationDataTranslationStorage) Get(ctx context.Context, key string, lang string) (*localization.Translation, error) {
	ret := _mock.Called(ctx, key, lang)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *localization.Translation
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (*localization.Translation, error)); ok {
		return returnFunc(ctx, key, lang)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) *localization.Translation); ok {
		r0 = returnFunc(ctx, key, lang)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*localization.Translation)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, key, lang)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// LocalizationDataTranslationStorage_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type LocalizationDataTranslationStorage_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx
//   - key
//   - lang
func (_e *LocalizationDataTranslationStorage_Expecter) Get(ctx interface{}, key interface{}, lang interface{}) *LocalizationDataTranslationStorage_Get_Call {
	return &LocalizationDataTranslationStorage_Get_Call{Call: _e.mock.On("Get", ctx, key, lang)}
}

func (_c *LocalizationDataTranslationStorage_Get_Call) Run(run func(ctx context.Context, key string, lang string)) *LocalizationDataTranslationStorage_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *LocalizationDataTranslationStorage_Get_Call) Return(translation *localization.Translation, err error) *LocalizationDataTranslationStorage_Get_Call {
	_c.Call.Return(translation, err)
	return _c
}

func (_c *LocalizationDataTranslationStorage_Get_Call) RunAndReturn(run func(ctx context.Context, key string, lang string) (*localization.Translation, error)) *LocalizationDataTranslationStorage_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Merge provides a mock function for the type LocalizationDataTranslationStorage
func (_mock *LocalizationDataTranslationStorage) Merge(ctx context.Context, t ...*localization.TranslationByKey) error {
	var tmpRet mock.Arguments
	if len(t) > 0 {
		tmpRet = _mock.Called(ctx, t)
	} else {
		tmpRet = _mock.Called(ctx)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Merge")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ...*localization.TranslationByKey) error); ok {
		r0 = returnFunc(ctx, t...)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// LocalizationDataTranslationStorage_Merge_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Merge'
type LocalizationDataTranslationStorage_Merge_Call struct {
	*mock.Call
}

// Merge is a helper method to define mock.On call
//   - ctx
//   - t
func (_e *LocalizationDataTranslationStorage_Expecter) Merge(ctx interface{}, t ...interface{}) *LocalizationDataTranslationStorage_Merge_Call {
	return &LocalizationDataTranslationStorage_Merge_Call{Call: _e.mock.On("Merge",
		append([]interface{}{ctx}, t...)...)}
}

func (_c *LocalizationDataTranslationStorage_Merge_Call) Run(run func(ctx context.Context, t ...*localization.TranslationByKey)) *LocalizationDataTranslationStorage_Merge_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := args[1].([]*localization.TranslationByKey)
		run(args[0].(context.Context), variadicArgs...)
	})
	return _c
}

func (_c *LocalizationDataTranslationStorage_Merge_Call) Return(err error) *LocalizationDataTranslationStorage_Merge_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *LocalizationDataTranslationStorage_Merge_Call) RunAndReturn(run func(ctx context.Context, t ...*localization.TranslationByKey) error) *LocalizationDataTranslationStorage_Merge_Call {
	_c.Call.Return(run)
	return _c
}

// Search provides a mock function for the type LocalizationDataTranslationStorage
func (_mock *LocalizationDataTranslationStorage) Search(ctx context.Context, cr *kit.PagingRequestG[localization.GetTranslationsCriteria]) (*kit.PagingResponseG[localization.TranslationByKey], error) {
	ret := _mock.Called(ctx, cr)

	if len(ret) == 0 {
		panic("no return value specified for Search")
	}

	var r0 *kit.PagingResponseG[localization.TranslationByKey]
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *kit.PagingRequestG[localization.GetTranslationsCriteria]) (*kit.PagingResponseG[localization.TranslationByKey], error)); ok {
		return returnFunc(ctx, cr)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *kit.PagingRequestG[localization.GetTranslationsCriteria]) *kit.PagingResponseG[localization.TranslationByKey]); ok {
		r0 = returnFunc(ctx, cr)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*kit.PagingResponseG[localization.TranslationByKey])
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *kit.PagingRequestG[localization.GetTranslationsCriteria]) error); ok {
		r1 = returnFunc(ctx, cr)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// LocalizationDataTranslationStorage_Search_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Search'
type LocalizationDataTranslationStorage_Search_Call struct {
	*mock.Call
}

// Search is a helper method to define mock.On call
//   - ctx
//   - cr
func (_e *LocalizationDataTranslationStorage_Expecter) Search(ctx interface{}, cr interface{}) *LocalizationDataTranslationStorage_Search_Call {
	return &LocalizationDataTranslationStorage_Search_Call{Call: _e.mock.On("Search", ctx, cr)}
}

func (_c *LocalizationDataTranslationStorage_Search_Call) Run(run func(ctx context.Context, cr *kit.PagingRequestG[localization.GetTranslationsCriteria])) *LocalizationDataTranslationStorage_Search_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*kit.PagingRequestG[localization.GetTranslationsCriteria]))
	})
	return _c
}

func (_c *LocalizationDataTranslationStorage_Search_Call) Return(pagingResponseG *kit.PagingResponseG[localization.TranslationByKey], err error) *LocalizationDataTranslationStorage_Search_Call {
	_c.Call.Return(pagingResponseG, err)
	return _c
}

func (_c *LocalizationDataTranslationStorage_Search_Call) RunAndReturn(run func(ctx context.Context, cr *kit.PagingRequestG[localization.GetTranslationsCriteria]) (*kit.PagingResponseG[localization.TranslationByKey], error)) *LocalizationDataTranslationStorage_Search_Call {
	_c.Call.Return(run)
	return _c
}
