// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"gitlab.com/algmib/kit/rpc"
)

// NewRpcDistributedKeys creates a new instance of RpcDistributedKeys. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRpcDistributedKeys(t interface {
	mock.TestingT
	Cleanup(func())
}) *RpcDistributedKeys {
	mock := &RpcDistributedKeys{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// RpcDistributedKeys is an autogenerated mock type for the DistributedKeys type
type RpcDistributedKeys struct {
	mock.Mock
}

type RpcDistributedKeys_Expecter struct {
	mock *mock.Mock
}

func (_m *RpcDistributedKeys) EXPECT() *RpcDistributedKeys_Expecter {
	return &RpcDistributedKeys_Expecter{mock: &_m.Mock}
}

// Check provides a mock function for the type RpcDistributedKeys
func (_mock *RpcDistributedKeys) Check(key string) bool {
	ret := _mock.Called(key)

	if len(ret) == 0 {
		panic("no return value specified for Check")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func(string) bool); ok {
		r0 = returnFunc(key)
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// RpcDistributedKeys_Check_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Check'
type RpcDistributedKeys_Check_Call struct {
	*mock.Call
}

// Check is a helper method to define mock.On call
//   - key
func (_e *RpcDistributedKeys_Expecter) Check(key interface{}) *RpcDistributedKeys_Check_Call {
	return &RpcDistributedKeys_Check_Call{Call: _e.mock.On("Check", key)}
}

func (_c *RpcDistributedKeys_Check_Call) Run(run func(key string)) *RpcDistributedKeys_Check_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *RpcDistributedKeys_Check_Call) Return(b bool) *RpcDistributedKeys_Check_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *RpcDistributedKeys_Check_Call) RunAndReturn(run func(key string) bool) *RpcDistributedKeys_Check_Call {
	_c.Call.Return(run)
	return _c
}

// Remove provides a mock function for the type RpcDistributedKeys
func (_mock *RpcDistributedKeys) Remove(key string) {
	_mock.Called(key)
	return
}

// RpcDistributedKeys_Remove_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Remove'
type RpcDistributedKeys_Remove_Call struct {
	*mock.Call
}

// Remove is a helper method to define mock.On call
//   - key
func (_e *RpcDistributedKeys_Expecter) Remove(key interface{}) *RpcDistributedKeys_Remove_Call {
	return &RpcDistributedKeys_Remove_Call{Call: _e.mock.On("Remove", key)}
}

func (_c *RpcDistributedKeys_Remove_Call) Run(run func(key string)) *RpcDistributedKeys_Remove_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *RpcDistributedKeys_Remove_Call) Return() *RpcDistributedKeys_Remove_Call {
	_c.Call.Return()
	return _c
}

func (_c *RpcDistributedKeys_Remove_Call) RunAndReturn(run func(key string)) *RpcDistributedKeys_Remove_Call {
	_c.Run(run)
	return _c
}

// Set provides a mock function for the type RpcDistributedKeys
func (_mock *RpcDistributedKeys) Set(key string) {
	_mock.Called(key)
	return
}

// RpcDistributedKeys_Set_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Set'
type RpcDistributedKeys_Set_Call struct {
	*mock.Call
}

// Set is a helper method to define mock.On call
//   - key
func (_e *RpcDistributedKeys_Expecter) Set(key interface{}) *RpcDistributedKeys_Set_Call {
	return &RpcDistributedKeys_Set_Call{Call: _e.mock.On("Set", key)}
}

func (_c *RpcDistributedKeys_Set_Call) Run(run func(key string)) *RpcDistributedKeys_Set_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *RpcDistributedKeys_Set_Call) Return() *RpcDistributedKeys_Set_Call {
	_c.Call.Return()
	return _c
}

func (_c *RpcDistributedKeys_Set_Call) RunAndReturn(run func(key string)) *RpcDistributedKeys_Set_Call {
	_c.Run(run)
	return _c
}

// NewRpcClient creates a new instance of RpcClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRpcClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *RpcClient {
	mock := &RpcClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// RpcClient is an autogenerated mock type for the Client type
type RpcClient struct {
	mock.Mock
}

type RpcClient_Expecter struct {
	mock *mock.Mock
}

func (_m *RpcClient) EXPECT() *RpcClient_Expecter {
	return &RpcClient_Expecter{mock: &_m.Mock}
}

// Call provides a mock function for the type RpcClient
func (_mock *RpcClient) Call(ctx context.Context, msg *rpc.Message, callback rpc.ResponseCallback) error {
	ret := _mock.Called(ctx, msg, callback)

	if len(ret) == 0 {
		panic("no return value specified for Call")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *rpc.Message, rpc.ResponseCallback) error); ok {
		r0 = returnFunc(ctx, msg, callback)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// RpcClient_Call_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Call'
type RpcClient_Call_Call struct {
	*mock.Call
}

// Call is a helper method to define mock.On call
//   - ctx
//   - msg
//   - callback
func (_e *RpcClient_Expecter) Call(ctx interface{}, msg interface{}, callback interface{}) *RpcClient_Call_Call {
	return &RpcClient_Call_Call{Call: _e.mock.On("Call", ctx, msg, callback)}
}

func (_c *RpcClient_Call_Call) Run(run func(ctx context.Context, msg *rpc.Message, callback rpc.ResponseCallback)) *RpcClient_Call_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*rpc.Message), args[2].(rpc.ResponseCallback))
	})
	return _c
}

func (_c *RpcClient_Call_Call) Return(err error) *RpcClient_Call_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *RpcClient_Call_Call) RunAndReturn(run func(ctx context.Context, msg *rpc.Message, callback rpc.ResponseCallback) error) *RpcClient_Call_Call {
	_c.Call.Return(run)
	return _c
}

// Close provides a mock function for the type RpcClient
func (_mock *RpcClient) Close(ctx context.Context) {
	_mock.Called(ctx)
	return
}

// RpcClient_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type RpcClient_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
//   - ctx
func (_e *RpcClient_Expecter) Close(ctx interface{}) *RpcClient_Close_Call {
	return &RpcClient_Close_Call{Call: _e.mock.On("Close", ctx)}
}

func (_c *RpcClient_Close_Call) Run(run func(ctx context.Context)) *RpcClient_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *RpcClient_Close_Call) Return() *RpcClient_Close_Call {
	_c.Call.Return()
	return _c
}

func (_c *RpcClient_Close_Call) RunAndReturn(run func(ctx context.Context)) *RpcClient_Close_Call {
	_c.Run(run)
	return _c
}

// RegisterBodyTypeProvider provides a mock function for the type RpcClient
func (_mock *RpcClient) RegisterBodyTypeProvider(messageType rpc.MessageType, messageBodyTypeProvider rpc.MessageBodyTypeProvider) {
	_mock.Called(messageType, messageBodyTypeProvider)
	return
}

// RpcClient_RegisterBodyTypeProvider_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RegisterBodyTypeProvider'
type RpcClient_RegisterBodyTypeProvider_Call struct {
	*mock.Call
}

// RegisterBodyTypeProvider is a helper method to define mock.On call
//   - messageType
//   - messageBodyTypeProvider
func (_e *RpcClient_Expecter) RegisterBodyTypeProvider(messageType interface{}, messageBodyTypeProvider interface{}) *RpcClient_RegisterBodyTypeProvider_Call {
	return &RpcClient_RegisterBodyTypeProvider_Call{Call: _e.mock.On("RegisterBodyTypeProvider", messageType, messageBodyTypeProvider)}
}

func (_c *RpcClient_RegisterBodyTypeProvider_Call) Run(run func(messageType rpc.MessageType, messageBodyTypeProvider rpc.MessageBodyTypeProvider)) *RpcClient_RegisterBodyTypeProvider_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(rpc.MessageType), args[1].(rpc.MessageBodyTypeProvider))
	})
	return _c
}

func (_c *RpcClient_RegisterBodyTypeProvider_Call) Return() *RpcClient_RegisterBodyTypeProvider_Call {
	_c.Call.Return()
	return _c
}

func (_c *RpcClient_RegisterBodyTypeProvider_Call) RunAndReturn(run func(messageType rpc.MessageType, messageBodyTypeProvider rpc.MessageBodyTypeProvider)) *RpcClient_RegisterBodyTypeProvider_Call {
	_c.Run(run)
	return _c
}

// ResponseHandler provides a mock function for the type RpcClient
func (_mock *RpcClient) ResponseHandler(msg []byte) error {
	ret := _mock.Called(msg)

	if len(ret) == 0 {
		panic("no return value specified for ResponseHandler")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func([]byte) error); ok {
		r0 = returnFunc(msg)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// RpcClient_ResponseHandler_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ResponseHandler'
type RpcClient_ResponseHandler_Call struct {
	*mock.Call
}

// ResponseHandler is a helper method to define mock.On call
//   - msg
func (_e *RpcClient_Expecter) ResponseHandler(msg interface{}) *RpcClient_ResponseHandler_Call {
	return &RpcClient_ResponseHandler_Call{Call: _e.mock.On("ResponseHandler", msg)}
}

func (_c *RpcClient_ResponseHandler_Call) Run(run func(msg []byte)) *RpcClient_ResponseHandler_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].([]byte))
	})
	return _c
}

func (_c *RpcClient_ResponseHandler_Call) Return(err error) *RpcClient_ResponseHandler_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *RpcClient_ResponseHandler_Call) RunAndReturn(run func(msg []byte) error) *RpcClient_ResponseHandler_Call {
	_c.Call.Return(run)
	return _c
}

// SetExpirationCallback provides a mock function for the type RpcClient
func (_mock *RpcClient) SetExpirationCallback(callback rpc.Callback) {
	_mock.Called(callback)
	return
}

// RpcClient_SetExpirationCallback_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetExpirationCallback'
type RpcClient_SetExpirationCallback_Call struct {
	*mock.Call
}

// SetExpirationCallback is a helper method to define mock.On call
//   - callback
func (_e *RpcClient_Expecter) SetExpirationCallback(callback interface{}) *RpcClient_SetExpirationCallback_Call {
	return &RpcClient_SetExpirationCallback_Call{Call: _e.mock.On("SetExpirationCallback", callback)}
}

func (_c *RpcClient_SetExpirationCallback_Call) Run(run func(callback rpc.Callback)) *RpcClient_SetExpirationCallback_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(rpc.Callback))
	})
	return _c
}

func (_c *RpcClient_SetExpirationCallback_Call) Return() *RpcClient_SetExpirationCallback_Call {
	_c.Call.Return()
	return _c
}

func (_c *RpcClient_SetExpirationCallback_Call) RunAndReturn(run func(callback rpc.Callback)) *RpcClient_SetExpirationCallback_Call {
	_c.Run(run)
	return _c
}

// Start provides a mock function for the type RpcClient
func (_mock *RpcClient) Start(ctx context.Context) {
	_mock.Called(ctx)
	return
}

// RpcClient_Start_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Start'
type RpcClient_Start_Call struct {
	*mock.Call
}

// Start is a helper method to define mock.On call
//   - ctx
func (_e *RpcClient_Expecter) Start(ctx interface{}) *RpcClient_Start_Call {
	return &RpcClient_Start_Call{Call: _e.mock.On("Start", ctx)}
}

func (_c *RpcClient_Start_Call) Run(run func(ctx context.Context)) *RpcClient_Start_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *RpcClient_Start_Call) Return() *RpcClient_Start_Call {
	_c.Call.Return()
	return _c
}

func (_c *RpcClient_Start_Call) RunAndReturn(run func(ctx context.Context)) *RpcClient_Start_Call {
	_c.Run(run)
	return _c
}

// NewRpcServer creates a new instance of RpcServer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRpcServer(t interface {
	mock.TestingT
	Cleanup(func())
}) *RpcServer {
	mock := &RpcServer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// RpcServer is an autogenerated mock type for the Server type
type RpcServer struct {
	mock.Mock
}

type RpcServer_Expecter struct {
	mock *mock.Mock
}

func (_m *RpcServer) EXPECT() *RpcServer_Expecter {
	return &RpcServer_Expecter{mock: &_m.Mock}
}

// Close provides a mock function for the type RpcServer
func (_mock *RpcServer) Close(ctx context.Context) {
	_mock.Called(ctx)
	return
}

// RpcServer_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type RpcServer_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
//   - ctx
func (_e *RpcServer_Expecter) Close(ctx interface{}) *RpcServer_Close_Call {
	return &RpcServer_Close_Call{Call: _e.mock.On("Close", ctx)}
}

func (_c *RpcServer_Close_Call) Run(run func(ctx context.Context)) *RpcServer_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *RpcServer_Close_Call) Return() *RpcServer_Close_Call {
	_c.Call.Return()
	return _c
}

func (_c *RpcServer_Close_Call) RunAndReturn(run func(ctx context.Context)) *RpcServer_Close_Call {
	_c.Run(run)
	return _c
}

// RegisterType provides a mock function for the type RpcServer
func (_mock *RpcServer) RegisterType(messageType rpc.MessageType, callback rpc.Callback, messageBodyTypeProvider rpc.MessageBodyTypeProvider) {
	_mock.Called(messageType, callback, messageBodyTypeProvider)
	return
}

// RpcServer_RegisterType_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RegisterType'
type RpcServer_RegisterType_Call struct {
	*mock.Call
}

// RegisterType is a helper method to define mock.On call
//   - messageType
//   - callback
//   - messageBodyTypeProvider
func (_e *RpcServer_Expecter) RegisterType(messageType interface{}, callback interface{}, messageBodyTypeProvider interface{}) *RpcServer_RegisterType_Call {
	return &RpcServer_RegisterType_Call{Call: _e.mock.On("RegisterType", messageType, callback, messageBodyTypeProvider)}
}

func (_c *RpcServer_RegisterType_Call) Run(run func(messageType rpc.MessageType, callback rpc.Callback, messageBodyTypeProvider rpc.MessageBodyTypeProvider)) *RpcServer_RegisterType_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(rpc.MessageType), args[1].(rpc.Callback), args[2].(rpc.MessageBodyTypeProvider))
	})
	return _c
}

func (_c *RpcServer_RegisterType_Call) Return() *RpcServer_RegisterType_Call {
	_c.Call.Return()
	return _c
}

func (_c *RpcServer_RegisterType_Call) RunAndReturn(run func(messageType rpc.MessageType, callback rpc.Callback, messageBodyTypeProvider rpc.MessageBodyTypeProvider)) *RpcServer_RegisterType_Call {
	_c.Run(run)
	return _c
}

// RequestHandler provides a mock function for the type RpcServer
func (_mock *RpcServer) RequestHandler(msg []byte) error {
	ret := _mock.Called(msg)

	if len(ret) == 0 {
		panic("no return value specified for RequestHandler")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func([]byte) error); ok {
		r0 = returnFunc(msg)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// RpcServer_RequestHandler_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RequestHandler'
type RpcServer_RequestHandler_Call struct {
	*mock.Call
}

// RequestHandler is a helper method to define mock.On call
//   - msg
func (_e *RpcServer_Expecter) RequestHandler(msg interface{}) *RpcServer_RequestHandler_Call {
	return &RpcServer_RequestHandler_Call{Call: _e.mock.On("RequestHandler", msg)}
}

func (_c *RpcServer_RequestHandler_Call) Run(run func(msg []byte)) *RpcServer_RequestHandler_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].([]byte))
	})
	return _c
}

func (_c *RpcServer_RequestHandler_Call) Return(err error) *RpcServer_RequestHandler_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *RpcServer_RequestHandler_Call) RunAndReturn(run func(msg []byte) error) *RpcServer_RequestHandler_Call {
	_c.Call.Return(run)
	return _c
}

// Response provides a mock function for the type RpcServer
func (_mock *RpcServer) Response(ctx context.Context, msg *rpc.Message) error {
	ret := _mock.Called(ctx, msg)

	if len(ret) == 0 {
		panic("no return value specified for Response")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *rpc.Message) error); ok {
		r0 = returnFunc(ctx, msg)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// RpcServer_Response_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Response'
type RpcServer_Response_Call struct {
	*mock.Call
}

// Response is a helper method to define mock.On call
//   - ctx
//   - msg
func (_e *RpcServer_Expecter) Response(ctx interface{}, msg interface{}) *RpcServer_Response_Call {
	return &RpcServer_Response_Call{Call: _e.mock.On("Response", ctx, msg)}
}

func (_c *RpcServer_Response_Call) Run(run func(ctx context.Context, msg *rpc.Message)) *RpcServer_Response_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*rpc.Message))
	})
	return _c
}

func (_c *RpcServer_Response_Call) Return(err error) *RpcServer_Response_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *RpcServer_Response_Call) RunAndReturn(run func(ctx context.Context, msg *rpc.Message) error) *RpcServer_Response_Call {
	_c.Call.Return(run)
	return _c
}

// SetExpirationCallback provides a mock function for the type RpcServer
func (_mock *RpcServer) SetExpirationCallback(callback rpc.Callback) {
	_mock.Called(callback)
	return
}

// RpcServer_SetExpirationCallback_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetExpirationCallback'
type RpcServer_SetExpirationCallback_Call struct {
	*mock.Call
}

// SetExpirationCallback is a helper method to define mock.On call
//   - callback
func (_e *RpcServer_Expecter) SetExpirationCallback(callback interface{}) *RpcServer_SetExpirationCallback_Call {
	return &RpcServer_SetExpirationCallback_Call{Call: _e.mock.On("SetExpirationCallback", callback)}
}

func (_c *RpcServer_SetExpirationCallback_Call) Run(run func(callback rpc.Callback)) *RpcServer_SetExpirationCallback_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(rpc.Callback))
	})
	return _c
}

func (_c *RpcServer_SetExpirationCallback_Call) Return() *RpcServer_SetExpirationCallback_Call {
	_c.Call.Return()
	return _c
}

func (_c *RpcServer_SetExpirationCallback_Call) RunAndReturn(run func(callback rpc.Callback)) *RpcServer_SetExpirationCallback_Call {
	_c.Run(run)
	return _c
}

// Start provides a mock function for the type RpcServer
func (_mock *RpcServer) Start(ctx context.Context) {
	_mock.Called(ctx)
	return
}

// RpcServer_Start_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Start'
type RpcServer_Start_Call struct {
	*mock.Call
}

// Start is a helper method to define mock.On call
//   - ctx
func (_e *RpcServer_Expecter) Start(ctx interface{}) *RpcServer_Start_Call {
	return &RpcServer_Start_Call{Call: _e.mock.On("Start", ctx)}
}

func (_c *RpcServer_Start_Call) Run(run func(ctx context.Context)) *RpcServer_Start_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *RpcServer_Start_Call) Return() *RpcServer_Start_Call {
	_c.Call.Return()
	return _c
}

func (_c *RpcServer_Start_Call) RunAndReturn(run func(ctx context.Context)) *RpcServer_Start_Call {
	_c.Run(run)
	return _c
}
