// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/olivere/elastic/v7"
	mock "github.com/stretchr/testify/mock"
	"gitlab.com/algmib/kit/storages/elasticsearch/v7"
)

// NewV7Search creates a new instance of V7Search. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewV7Search(t interface {
	mock.TestingT
	Cleanup(func())
}) *V7Search {
	mock := &V7Search{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// V7Search is an autogenerated mock type for the Search type
type V7Search struct {
	mock.Mock
}

type V7Search_Expecter struct {
	mock *mock.Mock
}

func (_m *V7Search) EXPECT() *V7Search_Expecter {
	return &V7Search_Expecter{mock: &_m.Mock}
}

// Close provides a mock function for the type V7Search
func (_mock *V7Search) Close(ctx context.Context) {
	_mock.Called(ctx)
	return
}

// V7Search_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type V7Search_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
//   - ctx
func (_e *V7Search_Expecter) Close(ctx interface{}) *V7Search_Close_Call {
	return &V7Search_Close_Call{Call: _e.mock.On("Close", ctx)}
}

func (_c *V7Search_Close_Call) Run(run func(ctx context.Context)) *V7Search_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *V7Search_Close_Call) Return() *V7Search_Close_Call {
	_c.Call.Return()
	return _c
}

func (_c *V7Search_Close_Call) RunAndReturn(run func(ctx context.Context)) *V7Search_Close_Call {
	_c.Run(run)
	return _c
}

// Delete provides a mock function for the type V7Search
func (_mock *V7Search) Delete(ctx context.Context, index string, id string) error {
	ret := _mock.Called(ctx, index, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, index, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// V7Search_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type V7Search_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx
//   - index
//   - id
func (_e *V7Search_Expecter) Delete(ctx interface{}, index interface{}, id interface{}) *V7Search_Delete_Call {
	return &V7Search_Delete_Call{Call: _e.mock.On("Delete", ctx, index, id)}
}

func (_c *V7Search_Delete_Call) Run(run func(ctx context.Context, index string, id string)) *V7Search_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *V7Search_Delete_Call) Return(err error) *V7Search_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *V7Search_Delete_Call) RunAndReturn(run func(ctx context.Context, index string, id string) error) *V7Search_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteBulk provides a mock function for the type V7Search
func (_mock *V7Search) DeleteBulk(ctx context.Context, index string, ids []string) error {
	ret := _mock.Called(ctx, index, ids)

	if len(ret) == 0 {
		panic("no return value specified for DeleteBulk")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []string) error); ok {
		r0 = returnFunc(ctx, index, ids)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// V7Search_DeleteBulk_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteBulk'
type V7Search_DeleteBulk_Call struct {
	*mock.Call
}

// DeleteBulk is a helper method to define mock.On call
//   - ctx
//   - index
//   - ids
func (_e *V7Search_Expecter) DeleteBulk(ctx interface{}, index interface{}, ids interface{}) *V7Search_DeleteBulk_Call {
	return &V7Search_DeleteBulk_Call{Call: _e.mock.On("DeleteBulk", ctx, index, ids)}
}

func (_c *V7Search_DeleteBulk_Call) Run(run func(ctx context.Context, index string, ids []string)) *V7Search_DeleteBulk_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].([]string))
	})
	return _c
}

func (_c *V7Search_DeleteBulk_Call) Return(err error) *V7Search_DeleteBulk_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *V7Search_DeleteBulk_Call) RunAndReturn(run func(ctx context.Context, index string, ids []string) error) *V7Search_DeleteBulk_Call {
	_c.Call.Return(run)
	return _c
}

// Exists provides a mock function for the type V7Search
func (_mock *V7Search) Exists(ctx context.Context, index string, id string) (bool, error) {
	ret := _mock.Called(ctx, index, id)

	if len(ret) == 0 {
		panic("no return value specified for Exists")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (bool, error)); ok {
		return returnFunc(ctx, index, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) bool); ok {
		r0 = returnFunc(ctx, index, id)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, index, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// V7Search_Exists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exists'
type V7Search_Exists_Call struct {
	*mock.Call
}

// Exists is a helper method to define mock.On call
//   - ctx
//   - index
//   - id
func (_e *V7Search_Expecter) Exists(ctx interface{}, index interface{}, id interface{}) *V7Search_Exists_Call {
	return &V7Search_Exists_Call{Call: _e.mock.On("Exists", ctx, index, id)}
}

func (_c *V7Search_Exists_Call) Run(run func(ctx context.Context, index string, id string)) *V7Search_Exists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *V7Search_Exists_Call) Return(b bool, err error) *V7Search_Exists_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *V7Search_Exists_Call) RunAndReturn(run func(ctx context.Context, index string, id string) (bool, error)) *V7Search_Exists_Call {
	_c.Call.Return(run)
	return _c
}

// GetClient provides a mock function for the type V7Search
func (_mock *V7Search) GetClient() *elastic.Client {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetClient")
	}

	var r0 *elastic.Client
	if returnFunc, ok := ret.Get(0).(func() *elastic.Client); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*elastic.Client)
		}
	}
	return r0
}

// V7Search_GetClient_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetClient'
type V7Search_GetClient_Call struct {
	*mock.Call
}

// GetClient is a helper method to define mock.On call
func (_e *V7Search_Expecter) GetClient() *V7Search_GetClient_Call {
	return &V7Search_GetClient_Call{Call: _e.mock.On("GetClient")}
}

func (_c *V7Search_GetClient_Call) Run(run func()) *V7Search_GetClient_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *V7Search_GetClient_Call) Return(client *elastic.Client) *V7Search_GetClient_Call {
	_c.Call.Return(client)
	return _c
}

func (_c *V7Search_GetClient_Call) RunAndReturn(run func() *elastic.Client) *V7Search_GetClient_Call {
	_c.Call.Return(run)
	return _c
}

// Index provides a mock function for the type V7Search
func (_mock *V7Search) Index(ctx context.Context, index string, id string, data interface{}) error {
	ret := _mock.Called(ctx, index, id, data)

	if len(ret) == 0 {
		panic("no return value specified for Index")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, interface{}) error); ok {
		r0 = returnFunc(ctx, index, id, data)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// V7Search_Index_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Index'
type V7Search_Index_Call struct {
	*mock.Call
}

// Index is a helper method to define mock.On call
//   - ctx
//   - index
//   - id
//   - data
func (_e *V7Search_Expecter) Index(ctx interface{}, index interface{}, id interface{}, data interface{}) *V7Search_Index_Call {
	return &V7Search_Index_Call{Call: _e.mock.On("Index", ctx, index, id, data)}
}

func (_c *V7Search_Index_Call) Run(run func(ctx context.Context, index string, id string, data interface{})) *V7Search_Index_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(interface{}))
	})
	return _c
}

func (_c *V7Search_Index_Call) Return(err error) *V7Search_Index_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *V7Search_Index_Call) RunAndReturn(run func(ctx context.Context, index string, id string, data interface{}) error) *V7Search_Index_Call {
	_c.Call.Return(run)
	return _c
}

// IndexAsync provides a mock function for the type V7Search
func (_mock *V7Search) IndexAsync(ctx context.Context, index string, id string, data interface{}) {
	_mock.Called(ctx, index, id, data)
	return
}

// V7Search_IndexAsync_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IndexAsync'
type V7Search_IndexAsync_Call struct {
	*mock.Call
}

// IndexAsync is a helper method to define mock.On call
//   - ctx
//   - index
//   - id
//   - data
func (_e *V7Search_Expecter) IndexAsync(ctx interface{}, index interface{}, id interface{}, data interface{}) *V7Search_IndexAsync_Call {
	return &V7Search_IndexAsync_Call{Call: _e.mock.On("IndexAsync", ctx, index, id, data)}
}

func (_c *V7Search_IndexAsync_Call) Run(run func(ctx context.Context, index string, id string, data interface{})) *V7Search_IndexAsync_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(interface{}))
	})
	return _c
}

func (_c *V7Search_IndexAsync_Call) Return() *V7Search_IndexAsync_Call {
	_c.Call.Return()
	return _c
}

func (_c *V7Search_IndexAsync_Call) RunAndReturn(run func(ctx context.Context, index string, id string, data interface{})) *V7Search_IndexAsync_Call {
	_c.Run(run)
	return _c
}

// IndexBulk provides a mock function for the type V7Search
func (_mock *V7Search) IndexBulk(ctx context.Context, index string, docs map[string]interface{}) error {
	ret := _mock.Called(ctx, index, docs)

	if len(ret) == 0 {
		panic("no return value specified for IndexBulk")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, map[string]interface{}) error); ok {
		r0 = returnFunc(ctx, index, docs)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// V7Search_IndexBulk_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IndexBulk'
type V7Search_IndexBulk_Call struct {
	*mock.Call
}

// IndexBulk is a helper method to define mock.On call
//   - ctx
//   - index
//   - docs
func (_e *V7Search_Expecter) IndexBulk(ctx interface{}, index interface{}, docs interface{}) *V7Search_IndexBulk_Call {
	return &V7Search_IndexBulk_Call{Call: _e.mock.On("IndexBulk", ctx, index, docs)}
}

func (_c *V7Search_IndexBulk_Call) Run(run func(ctx context.Context, index string, docs map[string]interface{})) *V7Search_IndexBulk_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(map[string]interface{}))
	})
	return _c
}

func (_c *V7Search_IndexBulk_Call) Return(err error) *V7Search_IndexBulk_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *V7Search_IndexBulk_Call) RunAndReturn(run func(ctx context.Context, index string, docs map[string]interface{}) error) *V7Search_IndexBulk_Call {
	_c.Call.Return(run)
	return _c
}

// IndexBulkAsync provides a mock function for the type V7Search
func (_mock *V7Search) IndexBulkAsync(ctx context.Context, index string, docs map[string]interface{}) {
	_mock.Called(ctx, index, docs)
	return
}

// V7Search_IndexBulkAsync_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IndexBulkAsync'
type V7Search_IndexBulkAsync_Call struct {
	*mock.Call
}

// IndexBulkAsync is a helper method to define mock.On call
//   - ctx
//   - index
//   - docs
func (_e *V7Search_Expecter) IndexBulkAsync(ctx interface{}, index interface{}, docs interface{}) *V7Search_IndexBulkAsync_Call {
	return &V7Search_IndexBulkAsync_Call{Call: _e.mock.On("IndexBulkAsync", ctx, index, docs)}
}

func (_c *V7Search_IndexBulkAsync_Call) Run(run func(ctx context.Context, index string, docs map[string]interface{})) *V7Search_IndexBulkAsync_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(map[string]interface{}))
	})
	return _c
}

func (_c *V7Search_IndexBulkAsync_Call) Return() *V7Search_IndexBulkAsync_Call {
	_c.Call.Return()
	return _c
}

func (_c *V7Search_IndexBulkAsync_Call) RunAndReturn(run func(ctx context.Context, index string, docs map[string]interface{})) *V7Search_IndexBulkAsync_Call {
	_c.Run(run)
	return _c
}

// NewBuilder provides a mock function for the type V7Search
func (_mock *V7Search) NewBuilder() v7.IndexBuilder {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for NewBuilder")
	}

	var r0 v7.IndexBuilder
	if returnFunc, ok := ret.Get(0).(func() v7.IndexBuilder); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(v7.IndexBuilder)
		}
	}
	return r0
}

// V7Search_NewBuilder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NewBuilder'
type V7Search_NewBuilder_Call struct {
	*mock.Call
}

// NewBuilder is a helper method to define mock.On call
func (_e *V7Search_Expecter) NewBuilder() *V7Search_NewBuilder_Call {
	return &V7Search_NewBuilder_Call{Call: _e.mock.On("NewBuilder")}
}

func (_c *V7Search_NewBuilder_Call) Run(run func()) *V7Search_NewBuilder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *V7Search_NewBuilder_Call) Return(indexBuilder v7.IndexBuilder) *V7Search_NewBuilder_Call {
	_c.Call.Return(indexBuilder)
	return _c
}

func (_c *V7Search_NewBuilder_Call) RunAndReturn(run func() v7.IndexBuilder) *V7Search_NewBuilder_Call {
	_c.Call.Return(run)
	return _c
}

// Ping provides a mock function for the type V7Search
func (_mock *V7Search) Ping() bool {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Ping")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func() bool); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// V7Search_Ping_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Ping'
type V7Search_Ping_Call struct {
	*mock.Call
}

// Ping is a helper method to define mock.On call
func (_e *V7Search_Expecter) Ping() *V7Search_Ping_Call {
	return &V7Search_Ping_Call{Call: _e.mock.On("Ping")}
}

func (_c *V7Search_Ping_Call) Run(run func()) *V7Search_Ping_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *V7Search_Ping_Call) Return(b bool) *V7Search_Ping_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *V7Search_Ping_Call) RunAndReturn(run func() bool) *V7Search_Ping_Call {
	_c.Call.Return(run)
	return _c
}

// Refresh provides a mock function for the type V7Search
func (_mock *V7Search) Refresh(ctx context.Context, index string) error {
	ret := _mock.Called(ctx, index)

	if len(ret) == 0 {
		panic("no return value specified for Refresh")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, index)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// V7Search_Refresh_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Refresh'
type V7Search_Refresh_Call struct {
	*mock.Call
}

// Refresh is a helper method to define mock.On call
//   - ctx
//   - index
func (_e *V7Search_Expecter) Refresh(ctx interface{}, index interface{}) *V7Search_Refresh_Call {
	return &V7Search_Refresh_Call{Call: _e.mock.On("Refresh", ctx, index)}
}

func (_c *V7Search_Refresh_Call) Run(run func(ctx context.Context, index string)) *V7Search_Refresh_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *V7Search_Refresh_Call) Return(err error) *V7Search_Refresh_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *V7Search_Refresh_Call) RunAndReturn(run func(ctx context.Context, index string) error) *V7Search_Refresh_Call {
	_c.Call.Return(run)
	return _c
}

// NewV7IndexBuilder creates a new instance of V7IndexBuilder. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewV7IndexBuilder(t interface {
	mock.TestingT
	Cleanup(func())
}) *V7IndexBuilder {
	mock := &V7IndexBuilder{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// V7IndexBuilder is an autogenerated mock type for the IndexBuilder type
type V7IndexBuilder struct {
	mock.Mock
}

type V7IndexBuilder_Expecter struct {
	mock *mock.Mock
}

func (_m *V7IndexBuilder) EXPECT() *V7IndexBuilder_Expecter {
	return &V7IndexBuilder_Expecter{mock: &_m.Mock}
}

// Build provides a mock function for the type V7IndexBuilder
func (_mock *V7IndexBuilder) Build(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Build")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// V7IndexBuilder_Build_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Build'
type V7IndexBuilder_Build_Call struct {
	*mock.Call
}

// Build is a helper method to define mock.On call
//   - ctx
func (_e *V7IndexBuilder_Expecter) Build(ctx interface{}) *V7IndexBuilder_Build_Call {
	return &V7IndexBuilder_Build_Call{Call: _e.mock.On("Build", ctx)}
}

func (_c *V7IndexBuilder_Build_Call) Run(run func(ctx context.Context)) *V7IndexBuilder_Build_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *V7IndexBuilder_Build_Call) Return(err error) *V7IndexBuilder_Build_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *V7IndexBuilder_Build_Call) RunAndReturn(run func(ctx context.Context) error) *V7IndexBuilder_Build_Call {
	_c.Call.Return(run)
	return _c
}

// WithAlias provides a mock function for the type V7IndexBuilder
func (_mock *V7IndexBuilder) WithAlias(name string) v7.IndexBuilder {
	ret := _mock.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for WithAlias")
	}

	var r0 v7.IndexBuilder
	if returnFunc, ok := ret.Get(0).(func(string) v7.IndexBuilder); ok {
		r0 = returnFunc(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(v7.IndexBuilder)
		}
	}
	return r0
}

// V7IndexBuilder_WithAlias_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WithAlias'
type V7IndexBuilder_WithAlias_Call struct {
	*mock.Call
}

// WithAlias is a helper method to define mock.On call
//   - name
func (_e *V7IndexBuilder_Expecter) WithAlias(name interface{}) *V7IndexBuilder_WithAlias_Call {
	return &V7IndexBuilder_WithAlias_Call{Call: _e.mock.On("WithAlias", name)}
}

func (_c *V7IndexBuilder_WithAlias_Call) Run(run func(name string)) *V7IndexBuilder_WithAlias_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *V7IndexBuilder_WithAlias_Call) Return(indexBuilder v7.IndexBuilder) *V7IndexBuilder_WithAlias_Call {
	_c.Call.Return(indexBuilder)
	return _c
}

func (_c *V7IndexBuilder_WithAlias_Call) RunAndReturn(run func(name string) v7.IndexBuilder) *V7IndexBuilder_WithAlias_Call {
	_c.Call.Return(run)
	return _c
}

// WithExplicitMapping provides a mock function for the type V7IndexBuilder
func (_mock *V7IndexBuilder) WithExplicitMapping(mapping string) v7.IndexBuilder {
	ret := _mock.Called(mapping)

	if len(ret) == 0 {
		panic("no return value specified for WithExplicitMapping")
	}

	var r0 v7.IndexBuilder
	if returnFunc, ok := ret.Get(0).(func(string) v7.IndexBuilder); ok {
		r0 = returnFunc(mapping)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(v7.IndexBuilder)
		}
	}
	return r0
}

// V7IndexBuilder_WithExplicitMapping_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WithExplicitMapping'
type V7IndexBuilder_WithExplicitMapping_Call struct {
	*mock.Call
}

// WithExplicitMapping is a helper method to define mock.On call
//   - mapping
func (_e *V7IndexBuilder_Expecter) WithExplicitMapping(mapping interface{}) *V7IndexBuilder_WithExplicitMapping_Call {
	return &V7IndexBuilder_WithExplicitMapping_Call{Call: _e.mock.On("WithExplicitMapping", mapping)}
}

func (_c *V7IndexBuilder_WithExplicitMapping_Call) Run(run func(mapping string)) *V7IndexBuilder_WithExplicitMapping_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *V7IndexBuilder_WithExplicitMapping_Call) Return(indexBuilder v7.IndexBuilder) *V7IndexBuilder_WithExplicitMapping_Call {
	_c.Call.Return(indexBuilder)
	return _c
}

func (_c *V7IndexBuilder_WithExplicitMapping_Call) RunAndReturn(run func(mapping string) v7.IndexBuilder) *V7IndexBuilder_WithExplicitMapping_Call {
	_c.Call.Return(run)
	return _c
}

// WithIndex provides a mock function for the type V7IndexBuilder
func (_mock *V7IndexBuilder) WithIndex(name string) v7.IndexBuilder {
	ret := _mock.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for WithIndex")
	}

	var r0 v7.IndexBuilder
	if returnFunc, ok := ret.Get(0).(func(string) v7.IndexBuilder); ok {
		r0 = returnFunc(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(v7.IndexBuilder)
		}
	}
	return r0
}

// V7IndexBuilder_WithIndex_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WithIndex'
type V7IndexBuilder_WithIndex_Call struct {
	*mock.Call
}

// WithIndex is a helper method to define mock.On call
//   - name
func (_e *V7IndexBuilder_Expecter) WithIndex(name interface{}) *V7IndexBuilder_WithIndex_Call {
	return &V7IndexBuilder_WithIndex_Call{Call: _e.mock.On("WithIndex", name)}
}

func (_c *V7IndexBuilder_WithIndex_Call) Run(run func(name string)) *V7IndexBuilder_WithIndex_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *V7IndexBuilder_WithIndex_Call) Return(indexBuilder v7.IndexBuilder) *V7IndexBuilder_WithIndex_Call {
	_c.Call.Return(indexBuilder)
	return _c
}

func (_c *V7IndexBuilder_WithIndex_Call) RunAndReturn(run func(name string) v7.IndexBuilder) *V7IndexBuilder_WithIndex_Call {
	_c.Call.Return(run)
	return _c
}

// WithMappingModel provides a mock function for the type V7IndexBuilder
func (_mock *V7IndexBuilder) WithMappingModel(model interface{}) v7.IndexBuilder {
	ret := _mock.Called(model)

	if len(ret) == 0 {
		panic("no return value specified for WithMappingModel")
	}

	var r0 v7.IndexBuilder
	if returnFunc, ok := ret.Get(0).(func(interface{}) v7.IndexBuilder); ok {
		r0 = returnFunc(model)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(v7.IndexBuilder)
		}
	}
	return r0
}

// V7IndexBuilder_WithMappingModel_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WithMappingModel'
type V7IndexBuilder_WithMappingModel_Call struct {
	*mock.Call
}

// WithMappingModel is a helper method to define mock.On call
//   - model
func (_e *V7IndexBuilder_Expecter) WithMappingModel(model interface{}) *V7IndexBuilder_WithMappingModel_Call {
	return &V7IndexBuilder_WithMappingModel_Call{Call: _e.mock.On("WithMappingModel", model)}
}

func (_c *V7IndexBuilder_WithMappingModel_Call) Run(run func(model interface{})) *V7IndexBuilder_WithMappingModel_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(interface{}))
	})
	return _c
}

func (_c *V7IndexBuilder_WithMappingModel_Call) Return(indexBuilder v7.IndexBuilder) *V7IndexBuilder_WithMappingModel_Call {
	_c.Call.Return(indexBuilder)
	return _c
}

func (_c *V7IndexBuilder_WithMappingModel_Call) RunAndReturn(run func(model interface{}) v7.IndexBuilder) *V7IndexBuilder_WithMappingModel_Call {
	_c.Call.Return(run)
	return _c
}
