// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"io"

	"github.com/elastic/go-elasticsearch/v8"
	"github.com/mikhailbolshakov/kit/storages/elasticsearch/v8"
	mock "github.com/stretchr/testify/mock"
)

// NewV8DataBody creates a new instance of V8DataBody. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewV8DataBody(t interface {
	mock.TestingT
	Cleanup(func())
}) *V8DataBody {
	mock := &V8DataBody{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// V8DataBody is an autogenerated mock type for the DataBody type
type V8DataBody struct {
	mock.Mock
}

type V8DataBody_Expecter struct {
	mock *mock.Mock
}

func (_m *V8DataBody) EXPECT() *V8DataBody_Expecter {
	return &V8DataBody_Expecter{mock: &_m.Mock}
}

// Reader provides a mock function for the type V8DataBody
func (_mock *V8DataBody) Reader() io.Reader {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Reader")
	}

	var r0 io.Reader
	if returnFunc, ok := ret.Get(0).(func() io.Reader); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(io.Reader)
		}
	}
	return r0
}

// V8DataBody_Reader_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Reader'
type V8DataBody_Reader_Call struct {
	*mock.Call
}

// Reader is a helper method to define mock.On call
func (_e *V8DataBody_Expecter) Reader() *V8DataBody_Reader_Call {
	return &V8DataBody_Reader_Call{Call: _e.mock.On("Reader")}
}

func (_c *V8DataBody_Reader_Call) Run(run func()) *V8DataBody_Reader_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *V8DataBody_Reader_Call) Return(reader io.Reader) *V8DataBody_Reader_Call {
	_c.Call.Return(reader)
	return _c
}

func (_c *V8DataBody_Reader_Call) RunAndReturn(run func() io.Reader) *V8DataBody_Reader_Call {
	_c.Call.Return(run)
	return _c
}

// NewV8Index creates a new instance of V8Index. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewV8Index(t interface {
	mock.TestingT
	Cleanup(func())
}) *V8Index {
	mock := &V8Index{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// V8Index is an autogenerated mock type for the Index type
type V8Index struct {
	mock.Mock
}

type V8Index_Expecter struct {
	mock *mock.Mock
}

func (_m *V8Index) EXPECT() *V8Index_Expecter {
	return &V8Index_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type V8Index
func (_mock *V8Index) Create(ctx context.Context, index string, mapping v8.MappingBody) error {
	ret := _mock.Called(ctx, index, mapping)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, v8.MappingBody) error); ok {
		r0 = returnFunc(ctx, index, mapping)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// V8Index_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type V8Index_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx
//   - index
//   - mapping
func (_e *V8Index_Expecter) Create(ctx interface{}, index interface{}, mapping interface{}) *V8Index_Create_Call {
	return &V8Index_Create_Call{Call: _e.mock.On("Create", ctx, index, mapping)}
}

func (_c *V8Index_Create_Call) Run(run func(ctx context.Context, index string, mapping v8.MappingBody)) *V8Index_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(v8.MappingBody))
	})
	return _c
}

func (_c *V8Index_Create_Call) Return(err error) *V8Index_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *V8Index_Create_Call) RunAndReturn(run func(ctx context.Context, index string, mapping v8.MappingBody) error) *V8Index_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type V8Index
func (_mock *V8Index) Delete(ctx context.Context, indices []string) error {
	ret := _mock.Called(ctx, indices)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []string) error); ok {
		r0 = returnFunc(ctx, indices)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// V8Index_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type V8Index_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx
//   - indices
func (_e *V8Index_Expecter) Delete(ctx interface{}, indices interface{}) *V8Index_Delete_Call {
	return &V8Index_Delete_Call{Call: _e.mock.On("Delete", ctx, indices)}
}

func (_c *V8Index_Delete_Call) Run(run func(ctx context.Context, indices []string)) *V8Index_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]string))
	})
	return _c
}

func (_c *V8Index_Delete_Call) Return(err error) *V8Index_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *V8Index_Delete_Call) RunAndReturn(run func(ctx context.Context, indices []string) error) *V8Index_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteIndices provides a mock function for the type V8Index
func (_mock *V8Index) DeleteIndices(ctx context.Context, alias string) error {
	ret := _mock.Called(ctx, alias)

	if len(ret) == 0 {
		panic("no return value specified for DeleteIndices")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, alias)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// V8Index_DeleteIndices_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteIndices'
type V8Index_DeleteIndices_Call struct {
	*mock.Call
}

// DeleteIndices is a helper method to define mock.On call
//   - ctx
//   - alias
func (_e *V8Index_Expecter) DeleteIndices(ctx interface{}, alias interface{}) *V8Index_DeleteIndices_Call {
	return &V8Index_DeleteIndices_Call{Call: _e.mock.On("DeleteIndices", ctx, alias)}
}

func (_c *V8Index_DeleteIndices_Call) Run(run func(ctx context.Context, alias string)) *V8Index_DeleteIndices_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *V8Index_DeleteIndices_Call) Return(err error) *V8Index_DeleteIndices_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *V8Index_DeleteIndices_Call) RunAndReturn(run func(ctx context.Context, alias string) error) *V8Index_DeleteIndices_Call {
	_c.Call.Return(run)
	return _c
}

// Exists provides a mock function for the type V8Index
func (_mock *V8Index) Exists(ctx context.Context, index string) (bool, error) {
	ret := _mock.Called(ctx, index)

	if len(ret) == 0 {
		panic("no return value specified for Exists")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return returnFunc(ctx, index)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = returnFunc(ctx, index)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, index)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// V8Index_Exists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exists'
type V8Index_Exists_Call struct {
	*mock.Call
}

// Exists is a helper method to define mock.On call
//   - ctx
//   - index
func (_e *V8Index_Expecter) Exists(ctx interface{}, index interface{}) *V8Index_Exists_Call {
	return &V8Index_Exists_Call{Call: _e.mock.On("Exists", ctx, index)}
}

func (_c *V8Index_Exists_Call) Run(run func(ctx context.Context, index string)) *V8Index_Exists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *V8Index_Exists_Call) Return(b bool, err error) *V8Index_Exists_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *V8Index_Exists_Call) RunAndReturn(run func(ctx context.Context, index string) (bool, error)) *V8Index_Exists_Call {
	_c.Call.Return(run)
	return _c
}

// GetIndices provides a mock function for the type V8Index
func (_mock *V8Index) GetIndices(ctx context.Context, alias string) (*v8.GetIndicesResponse, error) {
	ret := _mock.Called(ctx, alias)

	if len(ret) == 0 {
		panic("no return value specified for GetIndices")
	}

	var r0 *v8.GetIndicesResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*v8.GetIndicesResponse, error)); ok {
		return returnFunc(ctx, alias)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *v8.GetIndicesResponse); ok {
		r0 = returnFunc(ctx, alias)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v8.GetIndicesResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, alias)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// V8Index_GetIndices_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetIndices'
type V8Index_GetIndices_Call struct {
	*mock.Call
}

// GetIndices is a helper method to define mock.On call
//   - ctx
//   - alias
func (_e *V8Index_Expecter) GetIndices(ctx interface{}, alias interface{}) *V8Index_GetIndices_Call {
	return &V8Index_GetIndices_Call{Call: _e.mock.On("GetIndices", ctx, alias)}
}

func (_c *V8Index_GetIndices_Call) Run(run func(ctx context.Context, alias string)) *V8Index_GetIndices_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *V8Index_GetIndices_Call) Return(getIndicesResponse *v8.GetIndicesResponse, err error) *V8Index_GetIndices_Call {
	_c.Call.Return(getIndicesResponse, err)
	return _c
}

func (_c *V8Index_GetIndices_Call) RunAndReturn(run func(ctx context.Context, alias string) (*v8.GetIndicesResponse, error)) *V8Index_GetIndices_Call {
	_c.Call.Return(run)
	return _c
}

// GetMapping provides a mock function for the type V8Index
func (_mock *V8Index) GetMapping(ctx context.Context, index string) (*v8.GetMappingResponse, error) {
	ret := _mock.Called(ctx, index)

	if len(ret) == 0 {
		panic("no return value specified for GetMapping")
	}

	var r0 *v8.GetMappingResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*v8.GetMappingResponse, error)); ok {
		return returnFunc(ctx, index)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *v8.GetMappingResponse); ok {
		r0 = returnFunc(ctx, index)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v8.GetMappingResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, index)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// V8Index_GetMapping_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMapping'
type V8Index_GetMapping_Call struct {
	*mock.Call
}

// GetMapping is a helper method to define mock.On call
//   - ctx
//   - index
func (_e *V8Index_Expecter) GetMapping(ctx interface{}, index interface{}) *V8Index_GetMapping_Call {
	return &V8Index_GetMapping_Call{Call: _e.mock.On("GetMapping", ctx, index)}
}

func (_c *V8Index_GetMapping_Call) Run(run func(ctx context.Context, index string)) *V8Index_GetMapping_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *V8Index_GetMapping_Call) Return(getMappingResponse *v8.GetMappingResponse, err error) *V8Index_GetMapping_Call {
	_c.Call.Return(getMappingResponse, err)
	return _c
}

func (_c *V8Index_GetMapping_Call) RunAndReturn(run func(ctx context.Context, index string) (*v8.GetMappingResponse, error)) *V8Index_GetMapping_Call {
	_c.Call.Return(run)
	return _c
}

// NewBuilder provides a mock function for the type V8Index
func (_mock *V8Index) NewBuilder() v8.IndexBuilder {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for NewBuilder")
	}

	var r0 v8.IndexBuilder
	if returnFunc, ok := ret.Get(0).(func() v8.IndexBuilder); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(v8.IndexBuilder)
		}
	}
	return r0
}

// V8Index_NewBuilder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NewBuilder'
type V8Index_NewBuilder_Call struct {
	*mock.Call
}

// NewBuilder is a helper method to define mock.On call
func (_e *V8Index_Expecter) NewBuilder() *V8Index_NewBuilder_Call {
	return &V8Index_NewBuilder_Call{Call: _e.mock.On("NewBuilder")}
}

func (_c *V8Index_NewBuilder_Call) Run(run func()) *V8Index_NewBuilder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *V8Index_NewBuilder_Call) Return(indexBuilder v8.IndexBuilder) *V8Index_NewBuilder_Call {
	_c.Call.Return(indexBuilder)
	return _c
}

func (_c *V8Index_NewBuilder_Call) RunAndReturn(run func() v8.IndexBuilder) *V8Index_NewBuilder_Call {
	_c.Call.Return(run)
	return _c
}

// PutMapping provides a mock function for the type V8Index
func (_mock *V8Index) PutMapping(ctx context.Context, index string, mapping v8.MappingBody) error {
	ret := _mock.Called(ctx, index, mapping)

	if len(ret) == 0 {
		panic("no return value specified for PutMapping")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, v8.MappingBody) error); ok {
		r0 = returnFunc(ctx, index, mapping)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// V8Index_PutMapping_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PutMapping'
type V8Index_PutMapping_Call struct {
	*mock.Call
}

// PutMapping is a helper method to define mock.On call
//   - ctx
//   - index
//   - mapping
func (_e *V8Index_Expecter) PutMapping(ctx interface{}, index interface{}, mapping interface{}) *V8Index_PutMapping_Call {
	return &V8Index_PutMapping_Call{Call: _e.mock.On("PutMapping", ctx, index, mapping)}
}

func (_c *V8Index_PutMapping_Call) Run(run func(ctx context.Context, index string, mapping v8.MappingBody)) *V8Index_PutMapping_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(v8.MappingBody))
	})
	return _c
}

func (_c *V8Index_PutMapping_Call) Return(err error) *V8Index_PutMapping_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *V8Index_PutMapping_Call) RunAndReturn(run func(ctx context.Context, index string, mapping v8.MappingBody) error) *V8Index_PutMapping_Call {
	_c.Call.Return(run)
	return _c
}

// Refresh provides a mock function for the type V8Index
func (_mock *V8Index) Refresh(ctx context.Context, index string) error {
	ret := _mock.Called(ctx, index)

	if len(ret) == 0 {
		panic("no return value specified for Refresh")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, index)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// V8Index_Refresh_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Refresh'
type V8Index_Refresh_Call struct {
	*mock.Call
}

// Refresh is a helper method to define mock.On call
//   - ctx
//   - index
func (_e *V8Index_Expecter) Refresh(ctx interface{}, index interface{}) *V8Index_Refresh_Call {
	return &V8Index_Refresh_Call{Call: _e.mock.On("Refresh", ctx, index)}
}

func (_c *V8Index_Refresh_Call) Run(run func(ctx context.Context, index string)) *V8Index_Refresh_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *V8Index_Refresh_Call) Return(err error) *V8Index_Refresh_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *V8Index_Refresh_Call) RunAndReturn(run func(ctx context.Context, index string) error) *V8Index_Refresh_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateAliases provides a mock function for the type V8Index
func (_mock *V8Index) UpdateAliases(ctx context.Context, action *v8.AliasAction) error {
	ret := _mock.Called(ctx, action)

	if len(ret) == 0 {
		panic("no return value specified for UpdateAliases")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *v8.AliasAction) error); ok {
		r0 = returnFunc(ctx, action)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// V8Index_UpdateAliases_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateAliases'
type V8Index_UpdateAliases_Call struct {
	*mock.Call
}

// UpdateAliases is a helper method to define mock.On call
//   - ctx
//   - action
func (_e *V8Index_Expecter) UpdateAliases(ctx interface{}, action interface{}) *V8Index_UpdateAliases_Call {
	return &V8Index_UpdateAliases_Call{Call: _e.mock.On("UpdateAliases", ctx, action)}
}

func (_c *V8Index_UpdateAliases_Call) Run(run func(ctx context.Context, action *v8.AliasAction)) *V8Index_UpdateAliases_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*v8.AliasAction))
	})
	return _c
}

func (_c *V8Index_UpdateAliases_Call) Return(err error) *V8Index_UpdateAliases_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *V8Index_UpdateAliases_Call) RunAndReturn(run func(ctx context.Context, action *v8.AliasAction) error) *V8Index_UpdateAliases_Call {
	_c.Call.Return(run)
	return _c
}

// NewV8Document creates a new instance of V8Document. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewV8Document(t interface {
	mock.TestingT
	Cleanup(func())
}) *V8Document {
	mock := &V8Document{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// V8Document is an autogenerated mock type for the Document type
type V8Document struct {
	mock.Mock
}

type V8Document_Expecter struct {
	mock *mock.Mock
}

func (_m *V8Document) EXPECT() *V8Document_Expecter {
	return &V8Document_Expecter{mock: &_m.Mock}
}

// Delete provides a mock function for the type V8Document
func (_mock *V8Document) Delete(ctx context.Context, index string, id string) error {
	ret := _mock.Called(ctx, index, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, index, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// V8Document_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type V8Document_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx
//   - index
//   - id
func (_e *V8Document_Expecter) Delete(ctx interface{}, index interface{}, id interface{}) *V8Document_Delete_Call {
	return &V8Document_Delete_Call{Call: _e.mock.On("Delete", ctx, index, id)}
}

func (_c *V8Document_Delete_Call) Run(run func(ctx context.Context, index string, id string)) *V8Document_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *V8Document_Delete_Call) Return(err error) *V8Document_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *V8Document_Delete_Call) RunAndReturn(run func(ctx context.Context, index string, id string) error) *V8Document_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Exists provides a mock function for the type V8Document
func (_mock *V8Document) Exists(ctx context.Context, index string, id string) (bool, error) {
	ret := _mock.Called(ctx, index, id)

	if len(ret) == 0 {
		panic("no return value specified for Exists")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (bool, error)); ok {
		return returnFunc(ctx, index, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) bool); ok {
		r0 = returnFunc(ctx, index, id)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, index, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// V8Document_Exists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exists'
type V8Document_Exists_Call struct {
	*mock.Call
}

// Exists is a helper method to define mock.On call
//   - ctx
//   - index
//   - id
func (_e *V8Document_Expecter) Exists(ctx interface{}, index interface{}, id interface{}) *V8Document_Exists_Call {
	return &V8Document_Exists_Call{Call: _e.mock.On("Exists", ctx, index, id)}
}

func (_c *V8Document_Exists_Call) Run(run func(ctx context.Context, index string, id string)) *V8Document_Exists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *V8Document_Exists_Call) Return(b bool, err error) *V8Document_Exists_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *V8Document_Exists_Call) RunAndReturn(run func(ctx context.Context, index string, id string) (bool, error)) *V8Document_Exists_Call {
	_c.Call.Return(run)
	return _c
}

// Index provides a mock function for the type V8Document
func (_mock *V8Document) Index(ctx context.Context, index string, id string, data v8.DataBody) error {
	ret := _mock.Called(ctx, index, id, data)

	if len(ret) == 0 {
		panic("no return value specified for Index")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, v8.DataBody) error); ok {
		r0 = returnFunc(ctx, index, id, data)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// V8Document_Index_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Index'
type V8Document_Index_Call struct {
	*mock.Call
}

// Index is a helper method to define mock.On call
//   - ctx
//   - index
//   - id
//   - data
func (_e *V8Document_Expecter) Index(ctx interface{}, index interface{}, id interface{}, data interface{}) *V8Document_Index_Call {
	return &V8Document_Index_Call{Call: _e.mock.On("Index", ctx, index, id, data)}
}

func (_c *V8Document_Index_Call) Run(run func(ctx context.Context, index string, id string, data v8.DataBody)) *V8Document_Index_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(v8.DataBody))
	})
	return _c
}

func (_c *V8Document_Index_Call) Return(err error) *V8Document_Index_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *V8Document_Index_Call) RunAndReturn(run func(ctx context.Context, index string, id string, data v8.DataBody) error) *V8Document_Index_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type V8Document
func (_mock *V8Document) Update(ctx context.Context, index string, id string, data v8.DataBody) error {
	ret := _mock.Called(ctx, index, id, data)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, v8.DataBody) error); ok {
		r0 = returnFunc(ctx, index, id, data)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// V8Document_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type V8Document_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx
//   - index
//   - id
//   - data
func (_e *V8Document_Expecter) Update(ctx interface{}, index interface{}, id interface{}, data interface{}) *V8Document_Update_Call {
	return &V8Document_Update_Call{Call: _e.mock.On("Update", ctx, index, id, data)}
}

func (_c *V8Document_Update_Call) Run(run func(ctx context.Context, index string, id string, data v8.DataBody)) *V8Document_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(v8.DataBody))
	})
	return _c
}

func (_c *V8Document_Update_Call) Return(err error) *V8Document_Update_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *V8Document_Update_Call) RunAndReturn(run func(ctx context.Context, index string, id string, data v8.DataBody) error) *V8Document_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewV8Search creates a new instance of V8Search. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewV8Search(t interface {
	mock.TestingT
	Cleanup(func())
}) *V8Search {
	mock := &V8Search{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// V8Search is an autogenerated mock type for the Search type
type V8Search struct {
	mock.Mock
}

type V8Search_Expecter struct {
	mock *mock.Mock
}

func (_m *V8Search) EXPECT() *V8Search_Expecter {
	return &V8Search_Expecter{mock: &_m.Mock}
}

// Search provides a mock function for the type V8Search
func (_mock *V8Search) Search(ctx context.Context, index string, query v8.QueryBody) (*v8.SearchResponse, error) {
	ret := _mock.Called(ctx, index, query)

	if len(ret) == 0 {
		panic("no return value specified for Search")
	}

	var r0 *v8.SearchResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, v8.QueryBody) (*v8.SearchResponse, error)); ok {
		return returnFunc(ctx, index, query)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, v8.QueryBody) *v8.SearchResponse); ok {
		r0 = returnFunc(ctx, index, query)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v8.SearchResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, v8.QueryBody) error); ok {
		r1 = returnFunc(ctx, index, query)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// V8Search_Search_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Search'
type V8Search_Search_Call struct {
	*mock.Call
}

// Search is a helper method to define mock.On call
//   - ctx
//   - index
//   - query
func (_e *V8Search_Expecter) Search(ctx interface{}, index interface{}, query interface{}) *V8Search_Search_Call {
	return &V8Search_Search_Call{Call: _e.mock.On("Search", ctx, index, query)}
}

func (_c *V8Search_Search_Call) Run(run func(ctx context.Context, index string, query v8.QueryBody)) *V8Search_Search_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(v8.QueryBody))
	})
	return _c
}

func (_c *V8Search_Search_Call) Return(searchResponse *v8.SearchResponse, err error) *V8Search_Search_Call {
	_c.Call.Return(searchResponse, err)
	return _c
}

func (_c *V8Search_Search_Call) RunAndReturn(run func(ctx context.Context, index string, query v8.QueryBody) (*v8.SearchResponse, error)) *V8Search_Search_Call {
	_c.Call.Return(run)
	return _c
}

// NewV8Es creates a new instance of V8Es. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewV8Es(t interface {
	mock.TestingT
	Cleanup(func())
}) *V8Es {
	mock := &V8Es{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// V8Es is an autogenerated mock type for the Es type
type V8Es struct {
	mock.Mock
}

type V8Es_Expecter struct {
	mock *mock.Mock
}

func (_m *V8Es) EXPECT() *V8Es_Expecter {
	return &V8Es_Expecter{mock: &_m.Mock}
}

// Close provides a mock function for the type V8Es
func (_mock *V8Es) Close(ctx context.Context) {
	_mock.Called(ctx)
	return
}

// V8Es_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type V8Es_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
//   - ctx
func (_e *V8Es_Expecter) Close(ctx interface{}) *V8Es_Close_Call {
	return &V8Es_Close_Call{Call: _e.mock.On("Close", ctx)}
}

func (_c *V8Es_Close_Call) Run(run func(ctx context.Context)) *V8Es_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *V8Es_Close_Call) Return() *V8Es_Close_Call {
	_c.Call.Return()
	return _c
}

func (_c *V8Es_Close_Call) RunAndReturn(run func(ctx context.Context)) *V8Es_Close_Call {
	_c.Run(run)
	return _c
}

// Document provides a mock function for the type V8Es
func (_mock *V8Es) Document() v8.Document {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Document")
	}

	var r0 v8.Document
	if returnFunc, ok := ret.Get(0).(func() v8.Document); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(v8.Document)
		}
	}
	return r0
}

// V8Es_Document_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Document'
type V8Es_Document_Call struct {
	*mock.Call
}

// Document is a helper method to define mock.On call
func (_e *V8Es_Expecter) Document() *V8Es_Document_Call {
	return &V8Es_Document_Call{Call: _e.mock.On("Document")}
}

func (_c *V8Es_Document_Call) Run(run func()) *V8Es_Document_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *V8Es_Document_Call) Return(document v8.Document) *V8Es_Document_Call {
	_c.Call.Return(document)
	return _c
}

func (_c *V8Es_Document_Call) RunAndReturn(run func() v8.Document) *V8Es_Document_Call {
	_c.Call.Return(run)
	return _c
}

// GetClient provides a mock function for the type V8Es
func (_mock *V8Es) GetClient() *elasticsearch.Client {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetClient")
	}

	var r0 *elasticsearch.Client
	if returnFunc, ok := ret.Get(0).(func() *elasticsearch.Client); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*elasticsearch.Client)
		}
	}
	return r0
}

// V8Es_GetClient_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetClient'
type V8Es_GetClient_Call struct {
	*mock.Call
}

// GetClient is a helper method to define mock.On call
func (_e *V8Es_Expecter) GetClient() *V8Es_GetClient_Call {
	return &V8Es_GetClient_Call{Call: _e.mock.On("GetClient")}
}

func (_c *V8Es_GetClient_Call) Run(run func()) *V8Es_GetClient_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *V8Es_GetClient_Call) Return(client *elasticsearch.Client) *V8Es_GetClient_Call {
	_c.Call.Return(client)
	return _c
}

func (_c *V8Es_GetClient_Call) RunAndReturn(run func() *elasticsearch.Client) *V8Es_GetClient_Call {
	_c.Call.Return(run)
	return _c
}

// Index provides a mock function for the type V8Es
func (_mock *V8Es) Index() v8.Index {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Index")
	}

	var r0 v8.Index
	if returnFunc, ok := ret.Get(0).(func() v8.Index); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(v8.Index)
		}
	}
	return r0
}

// V8Es_Index_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Index'
type V8Es_Index_Call struct {
	*mock.Call
}

// Index is a helper method to define mock.On call
func (_e *V8Es_Expecter) Index() *V8Es_Index_Call {
	return &V8Es_Index_Call{Call: _e.mock.On("Index")}
}

func (_c *V8Es_Index_Call) Run(run func()) *V8Es_Index_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *V8Es_Index_Call) Return(index v8.Index) *V8Es_Index_Call {
	_c.Call.Return(index)
	return _c
}

func (_c *V8Es_Index_Call) RunAndReturn(run func() v8.Index) *V8Es_Index_Call {
	_c.Call.Return(run)
	return _c
}

// Instance provides a mock function for the type V8Es
func (_mock *V8Es) Instance() v8.Instance {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Instance")
	}

	var r0 v8.Instance
	if returnFunc, ok := ret.Get(0).(func() v8.Instance); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(v8.Instance)
		}
	}
	return r0
}

// V8Es_Instance_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Instance'
type V8Es_Instance_Call struct {
	*mock.Call
}

// Instance is a helper method to define mock.On call
func (_e *V8Es_Expecter) Instance() *V8Es_Instance_Call {
	return &V8Es_Instance_Call{Call: _e.mock.On("Instance")}
}

func (_c *V8Es_Instance_Call) Run(run func()) *V8Es_Instance_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *V8Es_Instance_Call) Return(instance v8.Instance) *V8Es_Instance_Call {
	_c.Call.Return(instance)
	return _c
}

func (_c *V8Es_Instance_Call) RunAndReturn(run func() v8.Instance) *V8Es_Instance_Call {
	_c.Call.Return(run)
	return _c
}

// Ping provides a mock function for the type V8Es
func (_mock *V8Es) Ping() bool {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Ping")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func() bool); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// V8Es_Ping_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Ping'
type V8Es_Ping_Call struct {
	*mock.Call
}

// Ping is a helper method to define mock.On call
func (_e *V8Es_Expecter) Ping() *V8Es_Ping_Call {
	return &V8Es_Ping_Call{Call: _e.mock.On("Ping")}
}

func (_c *V8Es_Ping_Call) Run(run func()) *V8Es_Ping_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *V8Es_Ping_Call) Return(b bool) *V8Es_Ping_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *V8Es_Ping_Call) RunAndReturn(run func() bool) *V8Es_Ping_Call {
	_c.Call.Return(run)
	return _c
}

// Search provides a mock function for the type V8Es
func (_mock *V8Es) Search() v8.Search {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Search")
	}

	var r0 v8.Search
	if returnFunc, ok := ret.Get(0).(func() v8.Search); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(v8.Search)
		}
	}
	return r0
}

// V8Es_Search_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Search'
type V8Es_Search_Call struct {
	*mock.Call
}

// Search is a helper method to define mock.On call
func (_e *V8Es_Expecter) Search() *V8Es_Search_Call {
	return &V8Es_Search_Call{Call: _e.mock.On("Search")}
}

func (_c *V8Es_Search_Call) Run(run func()) *V8Es_Search_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *V8Es_Search_Call) Return(search v8.Search) *V8Es_Search_Call {
	_c.Call.Return(search)
	return _c
}

func (_c *V8Es_Search_Call) RunAndReturn(run func() v8.Search) *V8Es_Search_Call {
	_c.Call.Return(run)
	return _c
}

// NewV8Instance creates a new instance of V8Instance. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewV8Instance(t interface {
	mock.TestingT
	Cleanup(func())
}) *V8Instance {
	mock := &V8Instance{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// V8Instance is an autogenerated mock type for the Instance type
type V8Instance struct {
	mock.Mock
}

type V8Instance_Expecter struct {
	mock *mock.Mock
}

func (_m *V8Instance) EXPECT() *V8Instance_Expecter {
	return &V8Instance_Expecter{mock: &_m.Mock}
}

// Document provides a mock function for the type V8Instance
func (_mock *V8Instance) Document() v8.Document {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Document")
	}

	var r0 v8.Document
	if returnFunc, ok := ret.Get(0).(func() v8.Document); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(v8.Document)
		}
	}
	return r0
}

// V8Instance_Document_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Document'
type V8Instance_Document_Call struct {
	*mock.Call
}

// Document is a helper method to define mock.On call
func (_e *V8Instance_Expecter) Document() *V8Instance_Document_Call {
	return &V8Instance_Document_Call{Call: _e.mock.On("Document")}
}

func (_c *V8Instance_Document_Call) Run(run func()) *V8Instance_Document_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *V8Instance_Document_Call) Return(document v8.Document) *V8Instance_Document_Call {
	_c.Call.Return(document)
	return _c
}

func (_c *V8Instance_Document_Call) RunAndReturn(run func() v8.Document) *V8Instance_Document_Call {
	_c.Call.Return(run)
	return _c
}

// Index provides a mock function for the type V8Instance
func (_mock *V8Instance) Index() v8.Index {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Index")
	}

	var r0 v8.Index
	if returnFunc, ok := ret.Get(0).(func() v8.Index); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(v8.Index)
		}
	}
	return r0
}

// V8Instance_Index_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Index'
type V8Instance_Index_Call struct {
	*mock.Call
}

// Index is a helper method to define mock.On call
func (_e *V8Instance_Expecter) Index() *V8Instance_Index_Call {
	return &V8Instance_Index_Call{Call: _e.mock.On("Index")}
}

func (_c *V8Instance_Index_Call) Run(run func()) *V8Instance_Index_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *V8Instance_Index_Call) Return(index v8.Index) *V8Instance_Index_Call {
	_c.Call.Return(index)
	return _c
}

func (_c *V8Instance_Index_Call) RunAndReturn(run func() v8.Index) *V8Instance_Index_Call {
	_c.Call.Return(run)
	return _c
}

// Search provides a mock function for the type V8Instance
func (_mock *V8Instance) Search() v8.Search {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Search")
	}

	var r0 v8.Search
	if returnFunc, ok := ret.Get(0).(func() v8.Search); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(v8.Search)
		}
	}
	return r0
}

// V8Instance_Search_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Search'
type V8Instance_Search_Call struct {
	*mock.Call
}

// Search is a helper method to define mock.On call
func (_e *V8Instance_Expecter) Search() *V8Instance_Search_Call {
	return &V8Instance_Search_Call{Call: _e.mock.On("Search")}
}

func (_c *V8Instance_Search_Call) Run(run func()) *V8Instance_Search_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *V8Instance_Search_Call) Return(search v8.Search) *V8Instance_Search_Call {
	_c.Call.Return(search)
	return _c
}

func (_c *V8Instance_Search_Call) RunAndReturn(run func() v8.Search) *V8Instance_Search_Call {
	_c.Call.Return(run)
	return _c
}

// NewV8IndexBuilder creates a new instance of V8IndexBuilder. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewV8IndexBuilder(t interface {
	mock.TestingT
	Cleanup(func())
}) *V8IndexBuilder {
	mock := &V8IndexBuilder{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// V8IndexBuilder is an autogenerated mock type for the IndexBuilder type
type V8IndexBuilder struct {
	mock.Mock
}

type V8IndexBuilder_Expecter struct {
	mock *mock.Mock
}

func (_m *V8IndexBuilder) EXPECT() *V8IndexBuilder_Expecter {
	return &V8IndexBuilder_Expecter{mock: &_m.Mock}
}

// Build provides a mock function for the type V8IndexBuilder
func (_mock *V8IndexBuilder) Build(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Build")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// V8IndexBuilder_Build_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Build'
type V8IndexBuilder_Build_Call struct {
	*mock.Call
}

// Build is a helper method to define mock.On call
//   - ctx
func (_e *V8IndexBuilder_Expecter) Build(ctx interface{}) *V8IndexBuilder_Build_Call {
	return &V8IndexBuilder_Build_Call{Call: _e.mock.On("Build", ctx)}
}

func (_c *V8IndexBuilder_Build_Call) Run(run func(ctx context.Context)) *V8IndexBuilder_Build_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *V8IndexBuilder_Build_Call) Return(err error) *V8IndexBuilder_Build_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *V8IndexBuilder_Build_Call) RunAndReturn(run func(ctx context.Context) error) *V8IndexBuilder_Build_Call {
	_c.Call.Return(run)
	return _c
}

// WithAlias provides a mock function for the type V8IndexBuilder
func (_mock *V8IndexBuilder) WithAlias(name string) v8.IndexBuilder {
	ret := _mock.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for WithAlias")
	}

	var r0 v8.IndexBuilder
	if returnFunc, ok := ret.Get(0).(func(string) v8.IndexBuilder); ok {
		r0 = returnFunc(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(v8.IndexBuilder)
		}
	}
	return r0
}

// V8IndexBuilder_WithAlias_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WithAlias'
type V8IndexBuilder_WithAlias_Call struct {
	*mock.Call
}

// WithAlias is a helper method to define mock.On call
//   - name
func (_e *V8IndexBuilder_Expecter) WithAlias(name interface{}) *V8IndexBuilder_WithAlias_Call {
	return &V8IndexBuilder_WithAlias_Call{Call: _e.mock.On("WithAlias", name)}
}

func (_c *V8IndexBuilder_WithAlias_Call) Run(run func(name string)) *V8IndexBuilder_WithAlias_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *V8IndexBuilder_WithAlias_Call) Return(indexBuilder v8.IndexBuilder) *V8IndexBuilder_WithAlias_Call {
	_c.Call.Return(indexBuilder)
	return _c
}

func (_c *V8IndexBuilder_WithAlias_Call) RunAndReturn(run func(name string) v8.IndexBuilder) *V8IndexBuilder_WithAlias_Call {
	_c.Call.Return(run)
	return _c
}

// WithExplicitMapping provides a mock function for the type V8IndexBuilder
func (_mock *V8IndexBuilder) WithExplicitMapping(mapping string) v8.IndexBuilder {
	ret := _mock.Called(mapping)

	if len(ret) == 0 {
		panic("no return value specified for WithExplicitMapping")
	}

	var r0 v8.IndexBuilder
	if returnFunc, ok := ret.Get(0).(func(string) v8.IndexBuilder); ok {
		r0 = returnFunc(mapping)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(v8.IndexBuilder)
		}
	}
	return r0
}

// V8IndexBuilder_WithExplicitMapping_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WithExplicitMapping'
type V8IndexBuilder_WithExplicitMapping_Call struct {
	*mock.Call
}

// WithExplicitMapping is a helper method to define mock.On call
//   - mapping
func (_e *V8IndexBuilder_Expecter) WithExplicitMapping(mapping interface{}) *V8IndexBuilder_WithExplicitMapping_Call {
	return &V8IndexBuilder_WithExplicitMapping_Call{Call: _e.mock.On("WithExplicitMapping", mapping)}
}

func (_c *V8IndexBuilder_WithExplicitMapping_Call) Run(run func(mapping string)) *V8IndexBuilder_WithExplicitMapping_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *V8IndexBuilder_WithExplicitMapping_Call) Return(indexBuilder v8.IndexBuilder) *V8IndexBuilder_WithExplicitMapping_Call {
	_c.Call.Return(indexBuilder)
	return _c
}

func (_c *V8IndexBuilder_WithExplicitMapping_Call) RunAndReturn(run func(mapping string) v8.IndexBuilder) *V8IndexBuilder_WithExplicitMapping_Call {
	_c.Call.Return(run)
	return _c
}

// WithIndex provides a mock function for the type V8IndexBuilder
func (_mock *V8IndexBuilder) WithIndex(name string) v8.IndexBuilder {
	ret := _mock.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for WithIndex")
	}

	var r0 v8.IndexBuilder
	if returnFunc, ok := ret.Get(0).(func(string) v8.IndexBuilder); ok {
		r0 = returnFunc(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(v8.IndexBuilder)
		}
	}
	return r0
}

// V8IndexBuilder_WithIndex_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WithIndex'
type V8IndexBuilder_WithIndex_Call struct {
	*mock.Call
}

// WithIndex is a helper method to define mock.On call
//   - name
func (_e *V8IndexBuilder_Expecter) WithIndex(name interface{}) *V8IndexBuilder_WithIndex_Call {
	return &V8IndexBuilder_WithIndex_Call{Call: _e.mock.On("WithIndex", name)}
}

func (_c *V8IndexBuilder_WithIndex_Call) Run(run func(name string)) *V8IndexBuilder_WithIndex_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *V8IndexBuilder_WithIndex_Call) Return(indexBuilder v8.IndexBuilder) *V8IndexBuilder_WithIndex_Call {
	_c.Call.Return(indexBuilder)
	return _c
}

func (_c *V8IndexBuilder_WithIndex_Call) RunAndReturn(run func(name string) v8.IndexBuilder) *V8IndexBuilder_WithIndex_Call {
	_c.Call.Return(run)
	return _c
}

// WithMappingModel provides a mock function for the type V8IndexBuilder
func (_mock *V8IndexBuilder) WithMappingModel(model interface{}) v8.IndexBuilder {
	ret := _mock.Called(model)

	if len(ret) == 0 {
		panic("no return value specified for WithMappingModel")
	}

	var r0 v8.IndexBuilder
	if returnFunc, ok := ret.Get(0).(func(interface{}) v8.IndexBuilder); ok {
		r0 = returnFunc(model)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(v8.IndexBuilder)
		}
	}
	return r0
}

// V8IndexBuilder_WithMappingModel_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WithMappingModel'
type V8IndexBuilder_WithMappingModel_Call struct {
	*mock.Call
}

// WithMappingModel is a helper method to define mock.On call
//   - model
func (_e *V8IndexBuilder_Expecter) WithMappingModel(model interface{}) *V8IndexBuilder_WithMappingModel_Call {
	return &V8IndexBuilder_WithMappingModel_Call{Call: _e.mock.On("WithMappingModel", model)}
}

func (_c *V8IndexBuilder_WithMappingModel_Call) Run(run func(model interface{})) *V8IndexBuilder_WithMappingModel_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(interface{}))
	})
	return _c
}

func (_c *V8IndexBuilder_WithMappingModel_Call) Return(indexBuilder v8.IndexBuilder) *V8IndexBuilder_WithMappingModel_Call {
	_c.Call.Return(indexBuilder)
	return _c
}

func (_c *V8IndexBuilder_WithMappingModel_Call) RunAndReturn(run func(model interface{}) v8.IndexBuilder) *V8IndexBuilder_WithMappingModel_Call {
	_c.Call.Return(run)
	return _c
}

// NewV8MappingBody creates a new instance of V8MappingBody. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewV8MappingBody(t interface {
	mock.TestingT
	Cleanup(func())
}) *V8MappingBody {
	mock := &V8MappingBody{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// V8MappingBody is an autogenerated mock type for the MappingBody type
type V8MappingBody struct {
	mock.Mock
}

type V8MappingBody_Expecter struct {
	mock *mock.Mock
}

func (_m *V8MappingBody) EXPECT() *V8MappingBody_Expecter {
	return &V8MappingBody_Expecter{mock: &_m.Mock}
}

// Reader provides a mock function for the type V8MappingBody
func (_mock *V8MappingBody) Reader() io.Reader {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Reader")
	}

	var r0 io.Reader
	if returnFunc, ok := ret.Get(0).(func() io.Reader); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(io.Reader)
		}
	}
	return r0
}

// V8MappingBody_Reader_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Reader'
type V8MappingBody_Reader_Call struct {
	*mock.Call
}

// Reader is a helper method to define mock.On call
func (_e *V8MappingBody_Expecter) Reader() *V8MappingBody_Reader_Call {
	return &V8MappingBody_Reader_Call{Call: _e.mock.On("Reader")}
}

func (_c *V8MappingBody_Reader_Call) Run(run func()) *V8MappingBody_Reader_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *V8MappingBody_Reader_Call) Return(reader io.Reader) *V8MappingBody_Reader_Call {
	_c.Call.Return(reader)
	return _c
}

func (_c *V8MappingBody_Reader_Call) RunAndReturn(run func() io.Reader) *V8MappingBody_Reader_Call {
	_c.Call.Return(run)
	return _c
}

// NewV8QueryBody creates a new instance of V8QueryBody. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewV8QueryBody(t interface {
	mock.TestingT
	Cleanup(func())
}) *V8QueryBody {
	mock := &V8QueryBody{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// V8QueryBody is an autogenerated mock type for the QueryBody type
type V8QueryBody struct {
	mock.Mock
}

type V8QueryBody_Expecter struct {
	mock *mock.Mock
}

func (_m *V8QueryBody) EXPECT() *V8QueryBody_Expecter {
	return &V8QueryBody_Expecter{mock: &_m.Mock}
}

// Reader provides a mock function for the type V8QueryBody
func (_mock *V8QueryBody) Reader() io.Reader {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Reader")
	}

	var r0 io.Reader
	if returnFunc, ok := ret.Get(0).(func() io.Reader); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(io.Reader)
		}
	}
	return r0
}

// V8QueryBody_Reader_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Reader'
type V8QueryBody_Reader_Call struct {
	*mock.Call
}

// Reader is a helper method to define mock.On call
func (_e *V8QueryBody_Expecter) Reader() *V8QueryBody_Reader_Call {
	return &V8QueryBody_Reader_Call{Call: _e.mock.On("Reader")}
}

func (_c *V8QueryBody_Reader_Call) Run(run func()) *V8QueryBody_Reader_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *V8QueryBody_Reader_Call) Return(reader io.Reader) *V8QueryBody_Reader_Call {
	_c.Call.Return(reader)
	return _c
}

func (_c *V8QueryBody_Reader_Call) RunAndReturn(run func() io.Reader) *V8QueryBody_Reader_Call {
	_c.Call.Return(run)
	return _c
}

// NewV8QueryBuilder creates a new instance of V8QueryBuilder. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewV8QueryBuilder(t interface {
	mock.TestingT
	Cleanup(func())
}) *V8QueryBuilder {
	mock := &V8QueryBuilder{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// V8QueryBuilder is an autogenerated mock type for the QueryBuilder type
type V8QueryBuilder struct {
	mock.Mock
}

type V8QueryBuilder_Expecter struct {
	mock *mock.Mock
}

func (_m *V8QueryBuilder) EXPECT() *V8QueryBuilder_Expecter {
	return &V8QueryBuilder_Expecter{mock: &_m.Mock}
}

// Build provides a mock function for the type V8QueryBuilder
func (_mock *V8QueryBuilder) Build() v8.QueryBody {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Build")
	}

	var r0 v8.QueryBody
	if returnFunc, ok := ret.Get(0).(func() v8.QueryBody); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(v8.QueryBody)
		}
	}
	return r0
}

// V8QueryBuilder_Build_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Build'
type V8QueryBuilder_Build_Call struct {
	*mock.Call
}

// Build is a helper method to define mock.On call
func (_e *V8QueryBuilder_Expecter) Build() *V8QueryBuilder_Build_Call {
	return &V8QueryBuilder_Build_Call{Call: _e.mock.On("Build")}
}

func (_c *V8QueryBuilder_Build_Call) Run(run func()) *V8QueryBuilder_Build_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *V8QueryBuilder_Build_Call) Return(queryBody v8.QueryBody) *V8QueryBuilder_Build_Call {
	_c.Call.Return(queryBody)
	return _c
}

func (_c *V8QueryBuilder_Build_Call) RunAndReturn(run func() v8.QueryBody) *V8QueryBuilder_Build_Call {
	_c.Call.Return(run)
	return _c
}
