// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/mikhailbolshakov/kit/vault"
	mock "github.com/stretchr/testify/mock"
)

// NewVaultVault creates a new instance of VaultVault. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewVaultVault(t interface {
	mock.TestingT
	Cleanup(func())
}) *VaultVault {
	mock := &VaultVault{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// VaultVault is an autogenerated mock type for the Vault type
type VaultVault struct {
	mock.Mock
}

type VaultVault_Expecter struct {
	mock *mock.Mock
}

func (_m *VaultVault) EXPECT() *VaultVault_Expecter {
	return &VaultVault_Expecter{mock: &_m.Mock}
}

// CreateRole provides a mock function for the type VaultVault
func (_mock *VaultVault) CreateRole(ctx context.Context, rq *vault.RoleRequest) (*vault.Role, error) {
	ret := _mock.Called(ctx, rq)

	if len(ret) == 0 {
		panic("no return value specified for CreateRole")
	}

	var r0 *vault.Role
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *vault.RoleRequest) (*vault.Role, error)); ok {
		return returnFunc(ctx, rq)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *vault.RoleRequest) *vault.Role); ok {
		r0 = returnFunc(ctx, rq)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*vault.Role)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *vault.RoleRequest) error); ok {
		r1 = returnFunc(ctx, rq)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// VaultVault_CreateRole_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateRole'
type VaultVault_CreateRole_Call struct {
	*mock.Call
}

// CreateRole is a helper method to define mock.On call
//   - ctx
//   - rq
func (_e *VaultVault_Expecter) CreateRole(ctx interface{}, rq interface{}) *VaultVault_CreateRole_Call {
	return &VaultVault_CreateRole_Call{Call: _e.mock.On("CreateRole", ctx, rq)}
}

func (_c *VaultVault_CreateRole_Call) Run(run func(ctx context.Context, rq *vault.RoleRequest)) *VaultVault_CreateRole_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*vault.RoleRequest))
	})
	return _c
}

func (_c *VaultVault_CreateRole_Call) Return(role *vault.Role, err error) *VaultVault_CreateRole_Call {
	_c.Call.Return(role, err)
	return _c
}

func (_c *VaultVault_CreateRole_Call) RunAndReturn(run func(ctx context.Context, rq *vault.RoleRequest) (*vault.Role, error)) *VaultVault_CreateRole_Call {
	_c.Call.Return(run)
	return _c
}

// EnablePKIEngine provides a mock function for the type VaultVault
func (_mock *VaultVault) EnablePKIEngine(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for EnablePKIEngine")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// VaultVault_EnablePKIEngine_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EnablePKIEngine'
type VaultVault_EnablePKIEngine_Call struct {
	*mock.Call
}

// EnablePKIEngine is a helper method to define mock.On call
//   - ctx
func (_e *VaultVault_Expecter) EnablePKIEngine(ctx interface{}) *VaultVault_EnablePKIEngine_Call {
	return &VaultVault_EnablePKIEngine_Call{Call: _e.mock.On("EnablePKIEngine", ctx)}
}

func (_c *VaultVault_EnablePKIEngine_Call) Run(run func(ctx context.Context)) *VaultVault_EnablePKIEngine_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *VaultVault_EnablePKIEngine_Call) Return(err error) *VaultVault_EnablePKIEngine_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *VaultVault_EnablePKIEngine_Call) RunAndReturn(run func(ctx context.Context) error) *VaultVault_EnablePKIEngine_Call {
	_c.Call.Return(run)
	return _c
}

// GenerateCSR provides a mock function for the type VaultVault
func (_mock *VaultVault) GenerateCSR(ctx context.Context, rq *vault.CSRRequest) (*vault.CSR, error) {
	ret := _mock.Called(ctx, rq)

	if len(ret) == 0 {
		panic("no return value specified for GenerateCSR")
	}

	var r0 *vault.CSR
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *vault.CSRRequest) (*vault.CSR, error)); ok {
		return returnFunc(ctx, rq)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *vault.CSRRequest) *vault.CSR); ok {
		r0 = returnFunc(ctx, rq)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*vault.CSR)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *vault.CSRRequest) error); ok {
		r1 = returnFunc(ctx, rq)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// VaultVault_GenerateCSR_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GenerateCSR'
type VaultVault_GenerateCSR_Call struct {
	*mock.Call
}

// GenerateCSR is a helper method to define mock.On call
//   - ctx
//   - rq
func (_e *VaultVault_Expecter) GenerateCSR(ctx interface{}, rq interface{}) *VaultVault_GenerateCSR_Call {
	return &VaultVault_GenerateCSR_Call{Call: _e.mock.On("GenerateCSR", ctx, rq)}
}

func (_c *VaultVault_GenerateCSR_Call) Run(run func(ctx context.Context, rq *vault.CSRRequest)) *VaultVault_GenerateCSR_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*vault.CSRRequest))
	})
	return _c
}

func (_c *VaultVault_GenerateCSR_Call) Return(cSR *vault.CSR, err error) *VaultVault_GenerateCSR_Call {
	_c.Call.Return(cSR, err)
	return _c
}

func (_c *VaultVault_GenerateCSR_Call) RunAndReturn(run func(ctx context.Context, rq *vault.CSRRequest) (*vault.CSR, error)) *VaultVault_GenerateCSR_Call {
	_c.Call.Return(run)
	return _c
}

// GenerateRootCA provides a mock function for the type VaultVault
func (_mock *VaultVault) GenerateRootCA(ctx context.Context, rq *vault.CertificateRequest) (*vault.Certificate, error) {
	ret := _mock.Called(ctx, rq)

	if len(ret) == 0 {
		panic("no return value specified for GenerateRootCA")
	}

	var r0 *vault.Certificate
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *vault.CertificateRequest) (*vault.Certificate, error)); ok {
		return returnFunc(ctx, rq)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *vault.CertificateRequest) *vault.Certificate); ok {
		r0 = returnFunc(ctx, rq)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*vault.Certificate)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *vault.CertificateRequest) error); ok {
		r1 = returnFunc(ctx, rq)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// VaultVault_GenerateRootCA_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GenerateRootCA'
type VaultVault_GenerateRootCA_Call struct {
	*mock.Call
}

// GenerateRootCA is a helper method to define mock.On call
//   - ctx
//   - rq
func (_e *VaultVault_Expecter) GenerateRootCA(ctx interface{}, rq interface{}) *VaultVault_GenerateRootCA_Call {
	return &VaultVault_GenerateRootCA_Call{Call: _e.mock.On("GenerateRootCA", ctx, rq)}
}

func (_c *VaultVault_GenerateRootCA_Call) Run(run func(ctx context.Context, rq *vault.CertificateRequest)) *VaultVault_GenerateRootCA_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*vault.CertificateRequest))
	})
	return _c
}

func (_c *VaultVault_GenerateRootCA_Call) Return(certificate *vault.Certificate, err error) *VaultVault_GenerateRootCA_Call {
	_c.Call.Return(certificate, err)
	return _c
}

func (_c *VaultVault_GenerateRootCA_Call) RunAndReturn(run func(ctx context.Context, rq *vault.CertificateRequest) (*vault.Certificate, error)) *VaultVault_GenerateRootCA_Call {
	_c.Call.Return(run)
	return _c
}

// GetCertificate provides a mock function for the type VaultVault
func (_mock *VaultVault) GetCertificate(ctx context.Context, serialNumber string) (*vault.CertificateResponse, error) {
	ret := _mock.Called(ctx, serialNumber)

	if len(ret) == 0 {
		panic("no return value specified for GetCertificate")
	}

	var r0 *vault.CertificateResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*vault.CertificateResponse, error)); ok {
		return returnFunc(ctx, serialNumber)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *vault.CertificateResponse); ok {
		r0 = returnFunc(ctx, serialNumber)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*vault.CertificateResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, serialNumber)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// VaultVault_GetCertificate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCertificate'
type VaultVault_GetCertificate_Call struct {
	*mock.Call
}

// GetCertificate is a helper method to define mock.On call
//   - ctx
//   - serialNumber
func (_e *VaultVault_Expecter) GetCertificate(ctx interface{}, serialNumber interface{}) *VaultVault_GetCertificate_Call {
	return &VaultVault_GetCertificate_Call{Call: _e.mock.On("GetCertificate", ctx, serialNumber)}
}

func (_c *VaultVault_GetCertificate_Call) Run(run func(ctx context.Context, serialNumber string)) *VaultVault_GetCertificate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *VaultVault_GetCertificate_Call) Return(certificateResponse *vault.CertificateResponse, err error) *VaultVault_GetCertificate_Call {
	_c.Call.Return(certificateResponse, err)
	return _c
}

func (_c *VaultVault_GetCertificate_Call) RunAndReturn(run func(ctx context.Context, serialNumber string) (*vault.CertificateResponse, error)) *VaultVault_GetCertificate_Call {
	_c.Call.Return(run)
	return _c
}

// GetChain provides a mock function for the type VaultVault
func (_mock *VaultVault) GetChain(ctx context.Context) (string, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetChain")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (string, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) string); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// VaultVault_GetChain_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetChain'
type VaultVault_GetChain_Call struct {
	*mock.Call
}

// GetChain is a helper method to define mock.On call
//   - ctx
func (_e *VaultVault_Expecter) GetChain(ctx interface{}) *VaultVault_GetChain_Call {
	return &VaultVault_GetChain_Call{Call: _e.mock.On("GetChain", ctx)}
}

func (_c *VaultVault_GetChain_Call) Run(run func(ctx context.Context)) *VaultVault_GetChain_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *VaultVault_GetChain_Call) Return(s string, err error) *VaultVault_GetChain_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *VaultVault_GetChain_Call) RunAndReturn(run func(ctx context.Context) (string, error)) *VaultVault_GetChain_Call {
	_c.Call.Return(run)
	return _c
}

// Init provides a mock function for the type VaultVault
func (_mock *VaultVault) Init(ctx context.Context, cfg *vault.Config) error {
	ret := _mock.Called(ctx, cfg)

	if len(ret) == 0 {
		panic("no return value specified for Init")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *vault.Config) error); ok {
		r0 = returnFunc(ctx, cfg)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// VaultVault_Init_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Init'
type VaultVault_Init_Call struct {
	*mock.Call
}

// Init is a helper method to define mock.On call
//   - ctx
//   - cfg
func (_e *VaultVault_Expecter) Init(ctx interface{}, cfg interface{}) *VaultVault_Init_Call {
	return &VaultVault_Init_Call{Call: _e.mock.On("Init", ctx, cfg)}
}

func (_c *VaultVault_Init_Call) Run(run func(ctx context.Context, cfg *vault.Config)) *VaultVault_Init_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*vault.Config))
	})
	return _c
}

func (_c *VaultVault_Init_Call) Return(err error) *VaultVault_Init_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *VaultVault_Init_Call) RunAndReturn(run func(ctx context.Context, cfg *vault.Config) error) *VaultVault_Init_Call {
	_c.Call.Return(run)
	return _c
}

// Issue provides a mock function for the type VaultVault
func (_mock *VaultVault) Issue(ctx context.Context, roleName string, rq *vault.IssueRequest) (*vault.IssueResponse, error) {
	ret := _mock.Called(ctx, roleName, rq)

	if len(ret) == 0 {
		panic("no return value specified for Issue")
	}

	var r0 *vault.IssueResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *vault.IssueRequest) (*vault.IssueResponse, error)); ok {
		return returnFunc(ctx, roleName, rq)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *vault.IssueRequest) *vault.IssueResponse); ok {
		r0 = returnFunc(ctx, roleName, rq)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*vault.IssueResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, *vault.IssueRequest) error); ok {
		r1 = returnFunc(ctx, roleName, rq)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// VaultVault_Issue_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Issue'
type VaultVault_Issue_Call struct {
	*mock.Call
}

// Issue is a helper method to define mock.On call
//   - ctx
//   - roleName
//   - rq
func (_e *VaultVault_Expecter) Issue(ctx interface{}, roleName interface{}, rq interface{}) *VaultVault_Issue_Call {
	return &VaultVault_Issue_Call{Call: _e.mock.On("Issue", ctx, roleName, rq)}
}

func (_c *VaultVault_Issue_Call) Run(run func(ctx context.Context, roleName string, rq *vault.IssueRequest)) *VaultVault_Issue_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(*vault.IssueRequest))
	})
	return _c
}

func (_c *VaultVault_Issue_Call) Return(issueResponse *vault.IssueResponse, err error) *VaultVault_Issue_Call {
	_c.Call.Return(issueResponse, err)
	return _c
}

func (_c *VaultVault_Issue_Call) RunAndReturn(run func(ctx context.Context, roleName string, rq *vault.IssueRequest) (*vault.IssueResponse, error)) *VaultVault_Issue_Call {
	_c.Call.Return(run)
	return _c
}

// Path provides a mock function for the type VaultVault
func (_mock *VaultVault) Path(path string) vault.Vault {
	ret := _mock.Called(path)

	if len(ret) == 0 {
		panic("no return value specified for Path")
	}

	var r0 vault.Vault
	if returnFunc, ok := ret.Get(0).(func(string) vault.Vault); ok {
		r0 = returnFunc(path)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(vault.Vault)
		}
	}
	return r0
}

// VaultVault_Path_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Path'
type VaultVault_Path_Call struct {
	*mock.Call
}

// Path is a helper method to define mock.On call
//   - path
func (_e *VaultVault_Expecter) Path(path interface{}) *VaultVault_Path_Call {
	return &VaultVault_Path_Call{Call: _e.mock.On("Path", path)}
}

func (_c *VaultVault_Path_Call) Run(run func(path string)) *VaultVault_Path_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *VaultVault_Path_Call) Return(vault1 vault.Vault) *VaultVault_Path_Call {
	_c.Call.Return(vault1)
	return _c
}

func (_c *VaultVault_Path_Call) RunAndReturn(run func(path string) vault.Vault) *VaultVault_Path_Call {
	_c.Call.Return(run)
	return _c
}

// SetSignedCertificate provides a mock function for the type VaultVault
func (_mock *VaultVault) SetSignedCertificate(ctx context.Context, rq *vault.SetSignedCertificateRequest) (*vault.SetSignedCertificateResponse, error) {
	ret := _mock.Called(ctx, rq)

	if len(ret) == 0 {
		panic("no return value specified for SetSignedCertificate")
	}

	var r0 *vault.SetSignedCertificateResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *vault.SetSignedCertificateRequest) (*vault.SetSignedCertificateResponse, error)); ok {
		return returnFunc(ctx, rq)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *vault.SetSignedCertificateRequest) *vault.SetSignedCertificateResponse); ok {
		r0 = returnFunc(ctx, rq)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*vault.SetSignedCertificateResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *vault.SetSignedCertificateRequest) error); ok {
		r1 = returnFunc(ctx, rq)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// VaultVault_SetSignedCertificate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetSignedCertificate'
type VaultVault_SetSignedCertificate_Call struct {
	*mock.Call
}

// SetSignedCertificate is a helper method to define mock.On call
//   - ctx
//   - rq
func (_e *VaultVault_Expecter) SetSignedCertificate(ctx interface{}, rq interface{}) *VaultVault_SetSignedCertificate_Call {
	return &VaultVault_SetSignedCertificate_Call{Call: _e.mock.On("SetSignedCertificate", ctx, rq)}
}

func (_c *VaultVault_SetSignedCertificate_Call) Run(run func(ctx context.Context, rq *vault.SetSignedCertificateRequest)) *VaultVault_SetSignedCertificate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*vault.SetSignedCertificateRequest))
	})
	return _c
}

func (_c *VaultVault_SetSignedCertificate_Call) Return(setSignedCertificateResponse *vault.SetSignedCertificateResponse, err error) *VaultVault_SetSignedCertificate_Call {
	_c.Call.Return(setSignedCertificateResponse, err)
	return _c
}

func (_c *VaultVault_SetSignedCertificate_Call) RunAndReturn(run func(ctx context.Context, rq *vault.SetSignedCertificateRequest) (*vault.SetSignedCertificateResponse, error)) *VaultVault_SetSignedCertificate_Call {
	_c.Call.Return(run)
	return _c
}

// Sign provides a mock function for the type VaultVault
func (_mock *VaultVault) Sign(ctx context.Context, roleName string, rq *vault.SignRequest) (*vault.Certificate, error) {
	ret := _mock.Called(ctx, roleName, rq)

	if len(ret) == 0 {
		panic("no return value specified for Sign")
	}

	var r0 *vault.Certificate
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *vault.SignRequest) (*vault.Certificate, error)); ok {
		return returnFunc(ctx, roleName, rq)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *vault.SignRequest) *vault.Certificate); ok {
		r0 = returnFunc(ctx, roleName, rq)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*vault.Certificate)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, *vault.SignRequest) error); ok {
		r1 = returnFunc(ctx, roleName, rq)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// VaultVault_Sign_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Sign'
type VaultVault_Sign_Call struct {
	*mock.Call
}

// Sign is a helper method to define mock.On call
//   - ctx
//   - roleName
//   - rq
func (_e *VaultVault_Expecter) Sign(ctx interface{}, roleName interface{}, rq interface{}) *VaultVault_Sign_Call {
	return &VaultVault_Sign_Call{Call: _e.mock.On("Sign", ctx, roleName, rq)}
}

func (_c *VaultVault_Sign_Call) Run(run func(ctx context.Context, roleName string, rq *vault.SignRequest)) *VaultVault_Sign_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(*vault.SignRequest))
	})
	return _c
}

func (_c *VaultVault_Sign_Call) Return(certificate *vault.Certificate, err error) *VaultVault_Sign_Call {
	_c.Call.Return(certificate, err)
	return _c
}

func (_c *VaultVault_Sign_Call) RunAndReturn(run func(ctx context.Context, roleName string, rq *vault.SignRequest) (*vault.Certificate, error)) *VaultVault_Sign_Call {
	_c.Call.Return(run)
	return _c
}

// SignIntermediateCA provides a mock function for the type VaultVault
func (_mock *VaultVault) SignIntermediateCA(ctx context.Context, rq *vault.SignRequest) (*vault.Certificate, error) {
	ret := _mock.Called(ctx, rq)

	if len(ret) == 0 {
		panic("no return value specified for SignIntermediateCA")
	}

	var r0 *vault.Certificate
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *vault.SignRequest) (*vault.Certificate, error)); ok {
		return returnFunc(ctx, rq)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *vault.SignRequest) *vault.Certificate); ok {
		r0 = returnFunc(ctx, rq)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*vault.Certificate)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *vault.SignRequest) error); ok {
		r1 = returnFunc(ctx, rq)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// VaultVault_SignIntermediateCA_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SignIntermediateCA'
type VaultVault_SignIntermediateCA_Call struct {
	*mock.Call
}

// SignIntermediateCA is a helper method to define mock.On call
//   - ctx
//   - rq
func (_e *VaultVault_Expecter) SignIntermediateCA(ctx interface{}, rq interface{}) *VaultVault_SignIntermediateCA_Call {
	return &VaultVault_SignIntermediateCA_Call{Call: _e.mock.On("SignIntermediateCA", ctx, rq)}
}

func (_c *VaultVault_SignIntermediateCA_Call) Run(run func(ctx context.Context, rq *vault.SignRequest)) *VaultVault_SignIntermediateCA_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*vault.SignRequest))
	})
	return _c
}

func (_c *VaultVault_SignIntermediateCA_Call) Return(certificate *vault.Certificate, err error) *VaultVault_SignIntermediateCA_Call {
	_c.Call.Return(certificate, err)
	return _c
}

func (_c *VaultVault_SignIntermediateCA_Call) RunAndReturn(run func(ctx context.Context, rq *vault.SignRequest) (*vault.Certificate, error)) *VaultVault_SignIntermediateCA_Call {
	_c.Call.Return(run)
	return _c
}

// UnmountPKIEngine provides a mock function for the type VaultVault
func (_mock *VaultVault) UnmountPKIEngine(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for UnmountPKIEngine")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// VaultVault_UnmountPKIEngine_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UnmountPKIEngine'
type VaultVault_UnmountPKIEngine_Call struct {
	*mock.Call
}

// UnmountPKIEngine is a helper method to define mock.On call
//   - ctx
func (_e *VaultVault_Expecter) UnmountPKIEngine(ctx interface{}) *VaultVault_UnmountPKIEngine_Call {
	return &VaultVault_UnmountPKIEngine_Call{Call: _e.mock.On("UnmountPKIEngine", ctx)}
}

func (_c *VaultVault_UnmountPKIEngine_Call) Run(run func(ctx context.Context)) *VaultVault_UnmountPKIEngine_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *VaultVault_UnmountPKIEngine_Call) Return(err error) *VaultVault_UnmountPKIEngine_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *VaultVault_UnmountPKIEngine_Call) RunAndReturn(run func(ctx context.Context) error) *VaultVault_UnmountPKIEngine_Call {
	_c.Call.Return(run)
	return _c
}
